export const CIUDADES_POR_ESTADO: Record<string, string[]> = {
  Amazonas: [
    "Puerto Ayacucho",
    "San Fernando de Atabapo",
    "Maroa",
    "San Carlos de Río Negro",
    "La Esmeralda",
  ],
  Anzoátegui: [
    "Barcelona",
    "Puerto La Cruz",
    "Lechería",
    "El Tigre",
    "Anaco",
    "Cantaura",
    "Píritu",
    "Clarines",
    "Aragua de Barcelona",
    "San Mateo",
  ],
  Apure: [
    "San Fernando de Apure",
    "Biruaca",
    "Achaguas",
    "Guasdualito",
    "Elorza",
    "Mantecal",
  ],
  Aragua: [
    "Maracay",
    "Turmero",
    "Cagua",
    "La Victoria",
    "Villa de Cura",
    "San Mateo",
    "El Limón",
    "Palo Negro",
    "Santa Cruz",
    "Camatagua",
  ],
  Barinas: [
    "Barinas",
    "Barinitas",
    "Santa Bárbara",
    "Socopó",
    "Ciudad Bolivia",
    "Sabaneta",
  ],
  Bolívar: [
    "Ciudad Bolívar",
    "Puerto Ordaz",
    "San Félix",
    "Upata",
    "Caicara del Orinoco",
    "Tumeremo",
    "El Callao",
    "Santa Elena de Uairén",
    "Ciudad Piar",
  ],
  Carabobo: [
    "Valencia",
    "Puerto Cabello",
    "Guacara",
    "Mariara",
    "San Diego",
    "Los Guayos",
    "Naguanagua",
    "San Joaquín",
    "Tocuyito",
    "Bejuma",
    "Montalbán",
    "Morón",
  ],
  Cojedes: [
    "San Carlos",
    "Tinaquillo",
    "El Baúl",
    "Las Vegas",
    "Libertad",
  ],
  "Delta Amacuro": [
    "Tucupita",
    "Pedernales",
    "Curiapo",
    "San José de Amacuro",
  ],
  "Distrito Capital": [
    "Caracas",
  ],
  Falcón: [
    "Coro",
    "Punto Fijo",
    "Tucacas",
    "Chichiriviche",
    "Dabajuro",
    "Judibana",
    "Los Taques",
    "Pueblo Nuevo",
    "Puerto Cumarebo",
    "Santa Ana de Coro",
  ],
  Guárico: [
    "San Juan de los Morros",
    "Calabozo",
    "Valle de la Pascua",
    "Zaraza",
    "Altagracia de Orituco",
    "Tucupido",
    "San José de Guaribe",
    "El Socorro",
  ],
  Lara: [
    "Barquisimeto",
    "Cabudare",
    "Carora",
    "El Tocuyo",
    "Quíbor",
    "Duaca",
    "Sarare",
    "Sanare",
    "Siquisique",
  ],
  Mérida: [
    "Mérida",
    "El Vigía",
    "Ejido",
    "Tovar",
    "Santa Cruz de Mora",
    "Mucuchíes",
    "Timotes",
    "Bailadores",
    "Lagunillas",
  ],
  Miranda: [
    "Los Teques",
    "Guarenas",
    "Guatire",
    "Charallave",
    "Ocumare del Tuy",
    "Cúa",
    "Santa Teresa del Tuy",
    "San Antonio de los Altos",
    "Carrizal",
    "Caucagüita",
    "Petare",
    "Baruta",
    "Chacao",
  ],
  Monagas: [
    "Maturín",
    "Punta de Mata",
    "Temblador",
    "Caripito",
    "Caripe",
    "Aguasay",
    "Barrancas del Orinoco",
  ],
  "Nueva Esparta": [
    "La Asunción",
    "Porlamar",
    "Pampatar",
    "Juan Griego",
    "El Valle del Espíritu Santo",
    "San Juan Bautista",
    "Santa Ana",
  ],
  Portuguesa: [
    "Guanare",
    "Acarigua",
    "Araure",
    "Biscucuy",
    "Boconoíto",
    "Ospino",
    "Turén",
    "Villa Bruzual",
  ],
  Sucre: [
    "Cumaná",
    "Carúpano",
    "Güiria",
    "Araya",
    "Casanay",
    "Cariaco",
    "Río Caribe",
    "Tunapuy",
  ],
  Táchira: [
    "San Cristóbal",
    "San Antonio del Táchira",
    "Táriba",
    "Rubio",
    "El Vigía",
    "La Grita",
    "Colón",
    "Ureña",
    "Capacho",
  ],
  Trujillo: [
    "Trujillo",
    "Valera",
    "Boconó",
    "Sabana de Mendoza",
    "Motatán",
    "Santa Ana",
    "Escuque",
  ],
  Vargas: [
    "La Guaira",
    "Catia La Mar",
    "Maiquetía",
    "Macuto",
    "Naiguatá",
    "Caraballeda",
  ],
  Yaracuy: [
    "San Felipe",
    "Yaritagua",
    "Chivacoa",
    "Nirgua",
    "Cocorote",
    "Aroa",
    "Urachiche",
  ],
  Zulia: [
    "Maracaibo",
    "Cabimas",
    "Ciudad Ojeda",
    "Machiques",
    "Santa Bárbara del Zulia",
    "San Carlos del Zulia",
    "La Villa del Rosario",
    "Mene Grande",
    "Santa Rita",
    "Lagunillas",
    "San Francisco",
  ],
};
