export const translations = {
    es: {
        welcome_default: "¡Hola! 👋 Soy el asistente virtual de **Red Salud**. Puedo ayudarte con información sobre:\n\n- 💰 Planes y precios\n- 🏥 Especialidades médicas\n- 📅 Cómo agendar citas\n- 💻 Telemedicina\n- ❓ Y mucho más\n\n¿En qué puedo ayudarte hoy?",
        welcome_doctor: "¡Hola Doctor! 👋 Bienvenido a su Agenda. Puedo ayudarle a reprogramar citas, verificar disponibilidad o contactar pacientes. ¿Qué necesita hacer hoy?",
        welcome_pricing: "¡Hola! Estás en la sección de precios. ¿Te gustaría saber más sobre nuestros planes para médicos o pacientes?",
        welcome_services: "¡Hola! ¿Buscas alguna especialidad médica en particular? Puedo ayudarte a encontrar lo que necesitas.",
        input_placeholder: "Escribe tu pregunta...",
        searching: "Buscando información...",
        typing: "Escribiendo...",
        error_message: "Lo siento, tuve un problema al procesar tu mensaje. Por favor intenta de nuevo o [contacta a soporte](/soporte) si el problema persiste.",
        clear_history: "Limpiar",
        header_title: "Asistente Red Salud",
        header_subtitle: "Disponible 24/7",
        disclaimer: "Respuestas generadas por IA. Verifica información importante.",
        suggestions_label: "Preguntas sugeridas:",
        feedback_positive: "Respuesta útil",
        feedback_negative: "Respuesta no útil",
        close_chat: "Cerrar chat",
        send_message: "Enviar mensaje"
    },
    en: {
        welcome_default: "Hello! 👋 I am the **Red Salud** virtual assistant. I can help you with information about:\n\n- 💰 Plans and pricing\n- 🏥 Medical specialties\n- 📅 How to schedule appointments\n- 💻 Telemedicine\n- ❓ And much more\n\nHow can I help you today?",
        welcome_doctor: "Hello Doctor! 👋 Welcome to your Agenda. I can help you reschedule appointments, check availability, or contact patients. What do you need to do today?",
        welcome_pricing: "Hello! You are in the pricing section. Would you like to know more about our plans for doctors or patients?",
        welcome_services: "Hello! Are you looking for a specific medical specialty? I can help you find what you need.",
        input_placeholder: "Type your question...",
        searching: "Searching for information...",
        typing: "Typing...",
        error_message: "I'm sorry, I had trouble processing your message. Please try again or [contact support](/soporte) if the problem persists.",
        clear_history: "Clear",
        header_title: "Red Salud Assistant",
        header_subtitle: "Available 24/7",
        disclaimer: "Responses generated by AI. Verify important information.",
        suggestions_label: "Suggested questions:",
        feedback_positive: "Helpful response",
        feedback_negative: "Unhelpful response",
        close_chat: "Close chat",
        send_message: "Send message"
    }
};

export type Language = "es" | "en";
export type TranslationKey = keyof typeof translations.es;

/**
 * Obtiene el diccionario de traducciones para el idioma especificado.
 * @param lang - El código del idioma ("es" o "en")
 * @returns El objeto con todas las traducciones para ese idioma
 */
export function getTranslations(lang: Language): typeof translations.es {
    return translations[lang];
}
