export const VENEZUELAN_UNIVERSITIES = [
    // Universidades Públicas Nacionales Autónomas
    { value: "Universidad Central de Venezuela (UCV)", label: "Universidad Central de Venezuela (UCV)" },
    { value: "Universidad de Los Andes (ULA)", label: "Universidad de Los Andes (ULA)" },
    { value: "Universidad de Carabobo (UC)", label: "Universidad de Carabobo (UC)" },
    { value: "Universidad de Oriente (UDO)", label: "Universidad de Oriente (UDO)" },
    { value: "Universidad del Zulia (LUZ)", label: "Universidad del Zulia (LUZ)" },
    { value: "Universidad Centroccidental Lisandro Alvarado (UCLA)", label: "Universidad Centroccidental Lisandro Alvarado (UCLA)" },
    { value: "Universidad Simón Bolívar (USB)", label: "Universidad Simón Bolívar (USB)" },

    // Universidades Públicas Nacionales Experimentales
    { value: "Universidad Nacional Experimental de los Llanos Occidentales Ezequiel Zamora (UNELLEZ)", label: "Universidad Nacional Experimental de los Llanos Occidentales Ezequiel Zamora (UNELLEZ)" },
    { value: "Universidad Nacional Experimental del Táchira (UNET)", label: "Universidad Nacional Experimental del Táchira (UNET)" },
    { value: "Universidad Nacional Abierta (UNA)", label: "Universidad Nacional Abierta (UNA)" },
    { value: "Universidad Pedagógica Experimental Libertador (UPEL)", label: "Universidad Pedagógica Experimental Libertador (UPEL)" },
    { value: "Universidad Nacional Experimental Politécnica de la Fuerza Armada Nacional (UNEFA)", label: "Universidad Nacional Experimental Politécnica de la Fuerza Armada Nacional (UNEFA)" },
    { value: "Universidad Nacional Experimental Simón Rodríguez (UNESR)", label: "Universidad Nacional Experimental Simón Rodríguez (UNESR)" },
    { value: "Universidad Bolivariana de Venezuela (UBV)", label: "Universidad Bolivariana de Venezuela (UBV)" },
    { value: "Universidad Nacional Experimental de Guayana (UNEG)", label: "Universidad Nacional Experimental de Guayana (UNEG)" },
    { value: "Universidad Nacional Experimental de Yaracuy (UNEY)", label: "Universidad Nacional Experimental de Yaracuy (UNEY)" },
    { value: "Universidad Marítima del Caribe (UMC)", label: "Universidad Marítima del Caribe (UMC)" },
    { value: "Universidad Politécnica Territorial de la Fuerza Armada Nacional (UNEFAN)", label: "Universidad Politécnica Territorial de la Fuerza Armada Nacional (UNEFAN)" },
    { value: "Universidad Nacional Experimental de las Artes (UNEARTE)", label: "Universidad Nacional Experimental de las Artes (UNEARTE)" },
    { value: "Universidad Nacional Experimental de la Seguridad (UNES)", label: "Universidad Nacional Experimental de la Seguridad (UNES)" },
    { value: "Universidad de Ciencias de la Salud (UCS)", label: "Universidad de Ciencias de la Salud (UCS)" },
    { value: "Universidad Deportiva del Sur", label: "Universidad Deportiva del Sur" },
    { value: "Universidad Nacional Experimental de los Llanos Centrales Rómulo Gallegos (UNERG)", label: "Universidad Nacional Experimental de los Llanos Centrales Rómulo Gallegos (UNERG)" },
    { value: "Universidad Nacional Experimental Francisco de Miranda (UNEFM)", label: "Universidad Nacional Experimental Francisco de Miranda (UNEFM)" },
    { value: "Universidad Nacional Experimental Sur del Lago (UNESUR)", label: "Universidad Nacional Experimental Sur del Lago (UNESUR)" },
    { value: "Universidad Nacional Experimental Rafael María Baralt (UNERMB)", label: "Universidad Nacional Experimental Rafael María Baralt (UNERMB)" },
    { value: "Universidad Nacional Experimental Politécnica Antonio José de Sucre (UNEXPO)", label: "Universidad Nacional Experimental Politécnica Antonio José de Sucre (UNEXPO)" },

    // Universidades Privadas
    { value: "Universidad Católica Andrés Bello (UCAB)", label: "Universidad Católica Andrés Bello (UCAB)" },
    { value: "Universidad Santa María (USM)", label: "Universidad Santa María (USM)" },
    { value: "Universidad Metropolitana (UNIMET)", label: "Universidad Metropolitana (UNIMET)" },
    { value: "Universidad Rafael Belloso Chacín (URBE)", label: "Universidad Rafael Belloso Chacín (URBE)" },
    { value: "Universidad José Antonio Páez (UJAP)", label: "Universidad José Antonio Páez (UJAP)" },
    { value: "Universidad Bicentenaria de Aragua (UBA)", label: "Universidad Bicentenaria de Aragua (UBA)" },
    { value: "Universidad Arturo Michelena (UAM)", label: "Universidad Arturo Michelena (UAM)" },
    { value: "Universidad Fermín Toro (UFT)", label: "Universidad Fermín Toro (UFT)" },
    { value: "Universidad Alejandro de Humboldt (UAH)", label: "Universidad Alejandro de Humboldt (UAH)" },
    { value: "Universidad Alonso de Ojeda (UNIOJEDA)", label: "Universidad Alonso de Ojeda (UNIOJEDA)" },
    { value: "Universidad Católica Cecilio Acosta (UNICA)", label: "Universidad Católica Cecilio Acosta (UNICA)" },
    { value: "Universidad Católica del Táchira (UCAT)", label: "Universidad Católica del Táchira (UCAT)" },
    { value: "Universidad Católica Santa Rosa (UCSAR)", label: "Universidad Católica Santa Rosa (UCSAR)" },
    { value: "Universidad Dr. José Gregorio Hernández", label: "Universidad Dr. José Gregorio Hernández" },
    { value: "Universidad José María Vargas (UJMV)", label: "Universidad José María Vargas (UJMV)" },
    { value: "Universidad Monteávila (UMA)", label: "Universidad Monteávila (UMA)" },
    { value: "Universidad Nororiental Gran Mariscal de Ayacucho (UGMA)", label: "Universidad Nororiental Gran Mariscal de Ayacucho (UGMA)" },
    { value: "Universidad Nueva Esparta (UNE)", label: "Universidad Nueva Esparta (UNE)" },
    { value: "Universidad Panamericana del Puerto (UNIPAP)", label: "Universidad Panamericana del Puerto (UNIPAP)" },
    { value: "Universidad Rafael Urdaneta (URU)", label: "Universidad Rafael Urdaneta (URU)" },
    { value: "Universidad Yacambú (UNY)", label: "Universidad Yacambú (UNY)" },
    { value: "Universidad Latinoamericana y del Caribe (ULAC)", label: "Universidad Latinoamericana y del Caribe (ULAC)" },
    { value: "Universidad de Margarita (UNIMAR)", label: "Universidad de Margarita (UNIMAR)" },
    { value: "Universidad Valle del Momboy (UVM)", label: "Universidad Valle del Momboy (UVM)" },
    { value: "Universidad de Falcón (UDEFA)", label: "Universidad de Falcón (UDEFA)" },
    { value: "Instituto de Estudios Superiores de Administración (IESA)", label: "Instituto de Estudios Superiores de Administración (IESA)" },
    { value: "Universidad Tecnológica del Centro (UNITEC)", label: "Universidad Tecnológica del Centro (UNITEC)" },
].sort((a, b) => a.label.localeCompare(b.label));
