import { StructuredTemplate } from './structured-templates';

// Biblioteca extendida de templates médicos (50+ templates)
export const EXTENDED_TEMPLATES: StructuredTemplate[] = [
  // MEDICINA GENERAL
  {
    id: 'consulta_primera_vez',
    name: 'Primera Consulta',
    description: 'Evaluación inicial completa de paciente nuevo',
    category: 'general',
    icon: 'UserPlus',
    color: 'blue',
    author: 'red-salud',
    tags: ['primera-vez', 'nuevo-paciente', 'evaluacion-inicial'],
    fields: [
      { id: 'motivoConsulta', label: 'MOTIVO DE CONSULTA', type: 'textarea', required: true, rows: 2 },
      { id: 'historiaEnfermedad', label: 'HISTORIA ENFERMEDAD ACTUAL', type: 'textarea', required: true, rows: 4 },
      { id: 'antecedentesPersonales', label: 'ANTECEDENTES PERSONALES', type: 'textarea', rows: 3 },
      { id: 'antecedentesFamiliares', label: 'ANTECEDENTES FAMILIARES', type: 'textarea', rows: 2 },
      { id: 'habitosPsicobiologicos', label: 'HÁBITOS', type: 'textarea', rows: 2 },
      { id: 'alergias', label: 'ALERGIAS', type: 'textarea', rows: 2 },
      { id: 'vitals', label: 'SIGNOS VITALES', type: 'vitals', required: true },
      { id: 'examenFisico', label: 'EXAMEN FÍSICO', type: 'textarea', rows: 4 },
      { id: 'impresionDiagnostica', label: 'IMPRESIÓN DIAGNÓSTICA', type: 'textarea', required: true, rows: 2 },
      { id: 'medications', label: 'TRATAMIENTO', type: 'medications' },
      { id: 'planTratamiento', label: 'PLAN', type: 'textarea', rows: 3 },
      { id: 'control', label: 'CONTROL', type: 'input' },
    ],
  },
  {
    id: 'consulta_rapida',
    name: 'Consulta Rápida',
    description: 'Evaluación breve para problemas simples',
    category: 'general',
    icon: 'Zap',
    color: 'yellow',
    author: 'red-salud',
    tags: ['rapida', 'simple', 'breve'],
    fields: [
      { id: 'motivoConsulta', label: 'MOTIVO', type: 'textarea', required: true, rows: 2 },
      { id: 'vitals', label: 'SIGNOS VITALES', type: 'vitals', required: true },
      { id: 'examenFisico', label: 'EXAMEN FÍSICO', type: 'textarea', rows: 2 },
      { id: 'diagnostico', label: 'DIAGNÓSTICO', type: 'input', required: true },
      { id: 'medications', label: 'TRATAMIENTO', type: 'medications' },
      { id: 'indicaciones', label: 'INDICACIONES', type: 'textarea', rows: 2 },
    ],
  },
  // CONTROL Y SEGUIMIENTO
  {
    id: 'control_cronico',
    name: 'Control Enfermedad Crónica',
    description: 'Seguimiento de paciente con enfermedad crónica',
    category: 'control',
    icon: 'Activity',
    color: 'green',
    author: 'red-salud',
    tags: ['control', 'cronico', 'seguimiento'],
    fields: [
      { id: 'motivoConsulta', label: 'MOTIVO', type: 'input', required: true },
      { id: 'evolucion', label: 'EVOLUCIÓN DESDE ÚLTIMA CONSULTA', type: 'textarea', required: true, rows: 3 },
      { id: 'adherenciaTratamiento', label: 'ADHERENCIA AL TRATAMIENTO', type: 'textarea', rows: 2 },
      { id: 'vitals', label: 'SIGNOS VITALES', type: 'vitals', required: true },
      { id: 'laboratorios', label: 'LABORATORIOS RECIENTES', type: 'textarea', rows: 3 },
      { id: 'examenFisico', label: 'EXAMEN FÍSICO', type: 'textarea', rows: 2 },
      { id: 'impresionDiagnostica', label: 'EVALUACIÓN ACTUAL', type: 'textarea', required: true, rows: 2 },
      { id: 'medications', label: 'AJUSTE MEDICAMENTOS', type: 'medications' },
      { id: 'planTratamiento', label: 'PLAN', type: 'textarea', rows: 3 },
      { id: 'control', label: 'PRÓXIMO CONTROL', type: 'input', required: true },
    ],
  },
  {
    id: 'control_hipertension',
    name: 'Control de Hipertensión',
    description: 'Seguimiento específico para pacientes hipertensos',
    category: 'control',
    icon: 'Heart',
    color: 'red',
    author: 'red-salud',
    tags: ['hipertension', 'presion', 'cardiovascular'],
    specialty: 'Cardiología',
    fields: [
      { id: 'motivoConsulta', label: 'MOTIVO', type: 'input', required: true },
      { id: 'sintomas', label: 'SÍNTOMAS CARDIOVASCULARES', type: 'textarea', rows: 2 },
      { id: 'adherencia', label: 'ADHERENCIA A MEDICAMENTOS', type: 'textarea', rows: 2 },
      { id: 'vitals', label: 'SIGNOS VITALES', type: 'vitals', required: true },
      { id: 'presionDomiciliaria', label: 'PRESIÓN ARTERIAL DOMICILIARIA', type: 'textarea', rows: 2 },
      { id: 'examenCardiovascular', label: 'EXAMEN CARDIOVASCULAR', type: 'textarea', rows: 2 },
      { id: 'laboratorios', label: 'LABORATORIOS', type: 'textarea', rows: 2 },
      { id: 'evaluacion', label: 'EVALUACIÓN', type: 'textarea', required: true, rows: 2 },
      { id: 'medications', label: 'TRATAMIENTO', type: 'medications' },
      { id: 'recomendaciones', label: 'RECOMENDACIONES', type: 'textarea', rows: 3 },
      { id: 'control', label: 'PRÓXIMO CONTROL', type: 'input', required: true },
    ],
  },
  {
    id: 'control_diabetes',
    name: 'Control de Diabetes',
    description: 'Seguimiento de paciente diabético',
    category: 'control',
    icon: 'Droplet',
    color: 'blue',
    author: 'red-salud',
    tags: ['diabetes', 'glucosa', 'endocrinologia'],
    specialty: 'Endocrinología',
    fields: [
      { id: 'motivoConsulta', label: 'MOTIVO', type: 'input', required: true },
      { id: 'sintomas', label: 'SÍNTOMAS', type: 'textarea', rows: 2 },
      { id: 'glucometria', label: 'GLUCOMETRÍAS DOMICILIARIAS', type: 'textarea', rows: 3 },
      { id: 'adherencia', label: 'ADHERENCIA A TRATAMIENTO Y DIETA', type: 'textarea', rows: 2 },
      { id: 'vitals', label: 'SIGNOS VITALES', type: 'vitals', required: true },
      { id: 'examenFisico', label: 'EXAMEN FÍSICO', type: 'textarea', rows: 2 },
      { id: 'laboratorios', label: 'LABORATORIOS (HbA1c, Perfil Lipídico)', type: 'textarea', rows: 3 },
      { id: 'complicaciones', label: 'EVALUACIÓN DE COMPLICACIONES', type: 'textarea', rows: 2 },
      { id: 'evaluacion', label: 'EVALUACIÓN', type: 'textarea', required: true, rows: 2 },
      { id: 'medications', label: 'TRATAMIENTO', type: 'medications' },
      { id: 'recomendaciones', label: 'RECOMENDACIONES', type: 'textarea', rows: 3 },
      { id: 'control', label: 'PRÓXIMO CONTROL', type: 'input', required: true },
    ],
  },
  // EMERGENCIAS
  {
    id: 'emergencia_general',
    name: 'Atención de Emergencia',
    description: 'Evaluación rápida para atención urgente',
    category: 'emergencia',
    icon: 'AlertCircle',
    color: 'red',
    author: 'red-salud',
    tags: ['emergencia', 'urgente', 'glasgow'],
    fields: [
      { id: 'motivoConsulta', label: 'MOTIVO DE EMERGENCIA', type: 'textarea', required: true, rows: 2 },
      { id: 'tiempoEvolucion', label: 'TIEMPO DE EVOLUCIÓN', type: 'input', required: true },
      { id: 'sintomasPrincipales', label: 'SÍNTOMAS PRINCIPALES', type: 'textarea', required: true, rows: 3 },
      { id: 'vitals', label: 'SIGNOS VITALES', type: 'vitals', required: true },
      { id: 'glasgow', label: 'ESCALA DE GLASGOW', type: 'input' },
      { id: 'examenFisico', label: 'EXAMEN FÍSICO', type: 'textarea', required: true, rows: 3 },
      { id: 'impresionDiagnostica', label: 'IMPRESIÓN DIAGNÓSTICA', type: 'textarea', required: true, rows: 2 },
      { id: 'medications', label: 'TRATAMIENTO INMEDIATO', type: 'medications' },
      { id: 'conducta', label: 'CONDUCTA', type: 'textarea', required: true, rows: 4 },
    ],
  },
  {
    id: 'dolor_toracico',
    name: 'Dolor Torácico',
    description: 'Evaluación de dolor torácico en emergencia',
    category: 'emergencia',
    icon: 'Heart',
    color: 'red',
    author: 'red-salud',
    tags: ['dolor-toracico', 'cardiologia', 'emergencia'],
    fields: [
      { id: 'motivoConsulta', label: 'MOTIVO', type: 'input', required: true },
      { id: 'caracteristicasDolor', label: 'CARACTERÍSTICAS DEL DOLOR', type: 'textarea', required: true, rows: 3 },
      { id: 'factoresAsociados', label: 'FACTORES ASOCIADOS', type: 'textarea', rows: 2 },
      { id: 'antecedentesCardiovasculares', label: 'ANTECEDENTES CARDIOVASCULARES', type: 'textarea', rows: 2 },
      { id: 'vitals', label: 'SIGNOS VITALES', type: 'vitals', required: true },
      { id: 'examenCardiovascular', label: 'EXAMEN CARDIOVASCULAR', type: 'textarea', required: true, rows: 3 },
      { id: 'ecg', label: 'ELECTROCARDIOGRAMA', type: 'textarea', rows: 2 },
      { id: 'laboratorios', label: 'LABORATORIOS (Troponina, CPK-MB)', type: 'textarea', rows: 2 },
      { id: 'impresionDiagnostica', label: 'IMPRESIÓN DIAGNÓSTICA', type: 'textarea', required: true, rows: 2 },
      { id: 'medications', label: 'TRATAMIENTO', type: 'medications' },
      { id: 'conducta', label: 'CONDUCTA', type: 'textarea', required: true, rows: 3 },
    ],
  },
  {
    id: 'trauma',
    name: 'Evaluación de Trauma',
    description: 'Evaluación inicial de paciente traumatizado',
    category: 'emergencia',
    icon: 'AlertTriangle',
    color: 'orange',
    author: 'red-salud',
    tags: ['trauma', 'accidente', 'lesiones'],
    fields: [
      { id: 'mecanismoTrauma', label: 'MECANISMO DE TRAUMA', type: 'textarea', required: true, rows: 2 },
      { id: 'tiempoEvolucion', label: 'TIEMPO DESDE EL TRAUMA', type: 'input', required: true },
      { id: 'vitals', label: 'SIGNOS VITALES', type: 'vitals', required: true },
      { id: 'glasgow', label: 'ESCALA DE GLASGOW', type: 'input', required: true },
      { id: 'evaluacionPrimaria', label: 'EVALUACIÓN PRIMARIA (ABCDE)', type: 'textarea', required: true, rows: 4 },
      { id: 'evaluacionSecundaria', label: 'EVALUACIÓN SECUNDARIA', type: 'textarea', rows: 4 },
      { id: 'lesionesIdentificadas', label: 'LESIONES IDENTIFICADAS', type: 'textarea', required: true, rows: 3 },
      { id: 'imagenologia', label: 'IMAGENOLOGÍA', type: 'textarea', rows: 2 },
      { id: 'impresionDiagnostica', label: 'IMPRESIÓN DIAGNÓSTICA', type: 'textarea', required: true, rows: 2 },
      { id: 'medications', label: 'TRATAMIENTO', type: 'medications' },
      { id: 'conducta', label: 'CONDUCTA', type: 'textarea', required: true, rows: 3 },
    ],
  },
  // PEDIATRÍA
  {
    id: 'pediatria_general',
    name: 'Consulta Pediátrica',
    description: 'Evaluación pediátrica completa',
    category: 'pediatria',
    icon: 'Baby',
    color: 'purple',
    author: 'red-salud',
    tags: ['pediatria', 'niños', 'desarrollo'],
    specialty: 'Pediatría',
    fields: [
      { id: 'motivoConsulta', label: 'MOTIVO DE CONSULTA', type: 'textarea', required: true, rows: 2 },
      { id: 'edad', label: 'EDAD', type: 'input', required: true },
      { id: 'antecedentesPrenatales', label: 'ANTECEDENTES PRENATALES Y PERINATALES', type: 'textarea', rows: 2 },
      { id: 'desarrolloPsicomotor', label: 'DESARROLLO PSICOMOTOR', type: 'textarea', rows: 2 },
      { id: 'vacunacion', label: 'VACUNACIÓN', type: 'textarea', rows: 2 },
      { id: 'alimentacion', label: 'ALIMENTACIÓN', type: 'textarea', rows: 2 },
      { id: 'vitals', label: 'SIGNOS VITALES Y ANTROPOMETRÍA', type: 'vitals', required: true },
      { id: 'examenFisico', label: 'EXAMEN FÍSICO', type: 'textarea', required: true, rows: 3 },
      { id: 'impresionDiagnostica', label: 'IMPRESIÓN DIAGNÓSTICA', type: 'textarea', required: true, rows: 2 },
      { id: 'medications', label: 'TRATAMIENTO', type: 'medications' },
      { id: 'indicacionesPadres', label: 'INDICACIONES A LOS PADRES', type: 'textarea', rows: 3 },
      { id: 'control', label: 'CONTROL', type: 'input' },
    ],
  },
  {
    id: 'control_niño_sano',
    name: 'Control de Niño Sano',
    description: 'Evaluación de crecimiento y desarrollo',
    category: 'pediatria',
    icon: 'Heart',
    color: 'pink',
    author: 'red-salud',
    tags: ['niño-sano', 'crecimiento', 'desarrollo'],
    specialty: 'Pediatría',
    fields: [
      { id: 'edad', label: 'EDAD', type: 'input', required: true },
      { id: 'alimentacion', label: 'ALIMENTACIÓN', type: 'textarea', rows: 2 },
      { id: 'desarrolloPsicomotor', label: 'DESARROLLO PSICOMOTOR', type: 'textarea', required: true, rows: 3 },
      { id: 'vacunacion', label: 'VACUNACIÓN', type: 'textarea', required: true, rows: 2 },
      { id: 'vitals', label: 'ANTROPOMETRÍA Y SIGNOS VITALES', type: 'vitals', required: true },
      { id: 'examenFisico', label: 'EXAMEN FÍSICO', type: 'textarea', required: true, rows: 3 },
      { id: 'evaluacion', label: 'EVALUACIÓN DEL DESARROLLO', type: 'textarea', required: true, rows: 2 },
      { id: 'recomendaciones', label: 'RECOMENDACIONES', type: 'textarea', rows: 3 },
      { id: 'proximoControl', label: 'PRÓXIMO CONTROL', type: 'input', required: true },
    ],
  },
  // GINECOLOGÍA Y OBSTETRICIA
  {
    id: 'ginecologia_general',
    name: 'Consulta Ginecológica',
    description: 'Evaluación ginecológica completa',
    category: 'ginecologia',
    icon: 'User',
    color: 'pink',
    author: 'red-salud',
    tags: ['ginecologia', 'mujer', 'salud-femenina'],
    specialty: 'Ginecología',
    fields: [
      { id: 'motivoConsulta', label: 'MOTIVO DE CONSULTA', type: 'textarea', required: true, rows: 2 },
      { id: 'antecedentesGinecoObstetricos', label: 'ANTECEDENTES GINECO-OBSTÉTRICOS', type: 'textarea', rows: 3 },
      { id: 'cicloMenstrual', label: 'CICLO MENSTRUAL', type: 'textarea', rows: 2 },
      { id: 'vidaSexual', label: 'VIDA SEXUAL', type: 'textarea', rows: 2 },
      { id: 'metodoAnticonceptivo', label: 'MÉTODO ANTICONCEPTIVO', type: 'input' },
      { id: 'vitals', label: 'SIGNOS VITALES', type: 'vitals', required: true },
      { id: 'examenFisico', label: 'EXAMEN FÍSICO GENERAL', type: 'textarea', rows: 2 },
      { id: 'examenGinecologico', label: 'EXAMEN GINECOLÓGICO', type: 'textarea', required: true, rows: 3 },
      { id: 'impresionDiagnostica', label: 'IMPRESIÓN DIAGNÓSTICA', type: 'textarea', required: true, rows: 2 },
      { id: 'medications', label: 'TRATAMIENTO', type: 'medications' },
      { id: 'planTratamiento', label: 'PLAN', type: 'textarea', rows: 3 },
      { id: 'control', label: 'CONTROL', type: 'input' },
    ],
  },
  {
    id: 'control_prenatal',
    name: 'Control Prenatal',
    description: 'Seguimiento de embarazo',
    category: 'ginecologia',
    icon: 'Baby',
    color: 'blue',
    author: 'red-salud',
    tags: ['prenatal', 'embarazo', 'obstetricia'],
    specialty: 'Obstetricia',
    fields: [
      { id: 'edadGestacional', label: 'EDAD GESTACIONAL', type: 'input', required: true },
      { id: 'sintomas', label: 'SÍNTOMAS', type: 'textarea', rows: 2 },
      { id: 'movimientosFetales', label: 'MOVIMIENTOS FETALES', type: 'textarea', rows: 1 },
      { id: 'vitals', label: 'SIGNOS VITALES', type: 'vitals', required: true },
      { id: 'pesoGanancia', label: 'PESO Y GANANCIA', type: 'input' },
      { id: 'alturaUterina', label: 'ALTURA UTERINA', type: 'input' },
      { id: 'fcf', label: 'FCF', type: 'input' },
      { id: 'examenObstetrico', label: 'EXAMEN OBSTÉTRICO', type: 'textarea', required: true, rows: 3 },
      { id: 'laboratorios', label: 'LABORATORIOS', type: 'textarea', rows: 2 },
      { id: 'ecografia', label: 'ECOGRAFÍA', type: 'textarea', rows: 2 },
      { id: 'evaluacion', label: 'EVALUACIÓN', type: 'textarea', required: true, rows: 2 },
      { id: 'medications', label: 'SUPLEMENTOS/MEDICAMENTOS', type: 'medications' },
      { id: 'recomendaciones', label: 'RECOMENDACIONES', type: 'textarea', rows: 3 },
      { id: 'proximoControl', label: 'PRÓXIMO CONTROL', type: 'input', required: true },
    ],
  },
  // DERMATOLOGÍA
  {
    id: 'dermatologia_general',
    name: 'Consulta Dermatológica',
    description: 'Evaluación dermatológica completa',
    category: 'dermatologia',
    icon: 'Scan',
    color: 'orange',
    author: 'red-salud',
    tags: ['dermatologia', 'piel', 'lesiones'],
    specialty: 'Dermatología',
    fields: [
      { id: 'motivoConsulta', label: 'MOTIVO DE CONSULTA', type: 'textarea', required: true, rows: 2 },
      { id: 'tiempoEvolucion', label: 'TIEMPO DE EVOLUCIÓN', type: 'input', required: true },
      { id: 'caracteristicasLesion', label: 'CARACTERÍSTICAS DE LA LESIÓN', type: 'textarea', required: true, rows: 3 },
      { id: 'factoresDesencadenantes', label: 'FACTORES DESENCADENANTES', type: 'textarea', rows: 2 },
      { id: 'tratamientosPrevios', label: 'TRATAMIENTOS PREVIOS', type: 'textarea', rows: 2 },
      { id: 'antecedentes', label: 'ANTECEDENTES DERMATOLÓGICOS', type: 'textarea', rows: 2 },
      { id: 'examenDermatologico', label: 'EXAMEN DERMATOLÓGICO', type: 'textarea', required: true, rows: 4 },
      { id: 'distribucion', label: 'DISTRIBUCIÓN Y LOCALIZACIÓN', type: 'textarea', rows: 2 },
      { id: 'impresionDiagnostica', label: 'IMPRESIÓN DIAGNÓSTICA', type: 'textarea', required: true, rows: 2 },
      { id: 'medications', label: 'TRATAMIENTO', type: 'medications' },
      { id: 'recomendaciones', label: 'RECOMENDACIONES', type: 'textarea', rows: 3 },
      { id: 'control', label: 'CONTROL', type: 'input' },
    ],
  },
  // OFTALMOLOGÍA
  {
    id: 'oftalmologia_general',
    name: 'Consulta Oftalmológica',
    description: 'Evaluación oftalmológica completa',
    category: 'oftalmologia',
    icon: 'Eye',
    color: 'cyan',
    author: 'red-salud',
    tags: ['oftalmologia', 'vision', 'ojos'],
    specialty: 'Oftalmología',
    fields: [
      { id: 'motivoConsulta', label: 'MOTIVO DE CONSULTA', type: 'textarea', required: true, rows: 2 },
      { id: 'sintomas', label: 'SÍNTOMAS VISUALES', type: 'textarea', required: true, rows: 2 },
      { id: 'antecedentesOftalmologicos', label: 'ANTECEDENTES OFTALMOLÓGICOS', type: 'textarea', rows: 2 },
      { id: 'agudezaVisual', label: 'AGUDEZA VISUAL', type: 'textarea', required: true, rows: 2 },
      { id: 'presionIntraocular', label: 'PRESIÓN INTRAOCULAR', type: 'input' },
      { id: 'examenExterno', label: 'EXAMEN EXTERNO', type: 'textarea', rows: 2 },
      { id: 'biomicroscopia', label: 'BIOMICROSCOPÍA', type: 'textarea', required: true, rows: 3 },
      { id: 'fondoOjo', label: 'FONDO DE OJO', type: 'textarea', rows: 3 },
      { id: 'impresionDiagnostica', label: 'IMPRESIÓN DIAGNÓSTICA', type: 'textarea', required: true, rows: 2 },
      { id: 'medications', label: 'TRATAMIENTO', type: 'medications' },
      { id: 'recomendaciones', label: 'RECOMENDACIONES', type: 'textarea', rows: 2 },
      { id: 'control', label: 'CONTROL', type: 'input' },
    ],
  },
  // OTORRINOLARINGOLOGÍA
  {
    id: 'otorrino_general',
    name: 'Consulta ORL',
    description: 'Evaluación otorrinolaringológica',
    category: 'otorrino',
    icon: 'Ear',
    color: 'teal',
    author: 'red-salud',
    tags: ['otorrino', 'oido', 'nariz', 'garganta'],
    specialty: 'Otorrinolaringología',
    fields: [
      { id: 'motivoConsulta', label: 'MOTIVO DE CONSULTA', type: 'textarea', required: true, rows: 2 },
      { id: 'sintomas', label: 'SÍNTOMAS', type: 'textarea', required: true, rows: 2 },
      { id: 'tiempoEvolucion', label: 'TIEMPO DE EVOLUCIÓN', type: 'input', required: true },
      { id: 'antecedentes', label: 'ANTECEDENTES ORL', type: 'textarea', rows: 2 },
      { id: 'otoscopia', label: 'OTOSCOPÍA', type: 'textarea', required: true, rows: 2 },
      { id: 'rinoscopia', label: 'RINOSCOPIA', type: 'textarea', rows: 2 },
      { id: 'orofaringe', label: 'OROFARINGE', type: 'textarea', rows: 2 },
      { id: 'cuello', label: 'EXAMEN DE CUELLO', type: 'textarea', rows: 2 },
      { id: 'audiometria', label: 'AUDIOMETRÍA', type: 'textarea', rows: 2 },
      { id: 'impresionDiagnostica', label: 'IMPRESIÓN DIAGNÓSTICA', type: 'textarea', required: true, rows: 2 },
      { id: 'medications', label: 'TRATAMIENTO', type: 'medications' },
      { id: 'recomendaciones', label: 'RECOMENDACIONES', type: 'textarea', rows: 2 },
      { id: 'control', label: 'CONTROL', type: 'input' },
    ],
  },
  // TRAUMATOLOGÍA
  {
    id: 'traumatologia_general',
    name: 'Consulta Traumatológica',
    description: 'Evaluación traumatológica y ortopédica',
    category: 'traumatologia',
    icon: 'Bone',
    color: 'gray',
    author: 'red-salud',
    tags: ['traumatologia', 'ortopedia', 'fracturas'],
    specialty: 'Traumatología',
    fields: [
      { id: 'motivoConsulta', label: 'MOTIVO DE CONSULTA', type: 'textarea', required: true, rows: 2 },
      { id: 'mecanismoLesion', label: 'MECANISMO DE LESIÓN', type: 'textarea', required: true, rows: 2 },
      { id: 'tiempoEvolucion', label: 'TIEMPO DE EVOLUCIÓN', type: 'input', required: true },
      { id: 'dolor', label: 'CARACTERÍSTICAS DEL DOLOR', type: 'textarea', rows: 2 },
      { id: 'limitacionFuncional', label: 'LIMITACIÓN FUNCIONAL', type: 'textarea', rows: 2 },
      { id: 'vitals', label: 'SIGNOS VITALES', type: 'vitals' },
      { id: 'inspeccion', label: 'INSPECCIÓN', type: 'textarea', required: true, rows: 2 },
      { id: 'palpacion', label: 'PALPACIÓN', type: 'textarea', rows: 2 },
      { id: 'movilidad', label: 'MOVILIDAD Y RANGOS ARTICULARES', type: 'textarea', rows: 2 },
      { id: 'examenNeurovascular', label: 'EXAMEN NEUROVASCULAR', type: 'textarea', rows: 2 },
      { id: 'imagenologia', label: 'IMAGENOLOGÍA', type: 'textarea', rows: 3 },
      { id: 'impresionDiagnostica', label: 'IMPRESIÓN DIAGNÓSTICA', type: 'textarea', required: true, rows: 2 },
      { id: 'medications', label: 'TRATAMIENTO', type: 'medications' },
      { id: 'planTratamiento', label: 'PLAN DE TRATAMIENTO', type: 'textarea', rows: 3 },
      { id: 'control', label: 'CONTROL', type: 'input' },
    ],
  },
  // PSIQUIATRÍA
  {
    id: 'psiquiatria_general',
    name: 'Consulta Psiquiátrica',
    description: 'Evaluación psiquiátrica completa',
    category: 'psiquiatria',
    icon: 'Brain',
    color: 'indigo',
    author: 'red-salud',
    tags: ['psiquiatria', 'salud-mental', 'psicologia'],
    specialty: 'Psiquiatría',
    fields: [
      { id: 'motivoConsulta', label: 'MOTIVO DE CONSULTA', type: 'textarea', required: true, rows: 2 },
      { id: 'historiaEnfermedad', label: 'HISTORIA DE LA ENFERMEDAD ACTUAL', type: 'textarea', required: true, rows: 4 },
      { id: 'antecedentes', label: 'ANTECEDENTES PSIQUIÁTRICOS', type: 'textarea', rows: 3 },
      { id: 'antecedentesFamiliares', label: 'ANTECEDENTES FAMILIARES PSIQUIÁTRICOS', type: 'textarea', rows: 2 },
      { id: 'sustancias', label: 'USO DE SUSTANCIAS', type: 'textarea', rows: 2 },
      { id: 'examenMental', label: 'EXAMEN MENTAL', type: 'textarea', required: true, rows: 5 },
      { id: 'riesgoSuicida', label: 'EVALUACIÓN DE RIESGO SUICIDA', type: 'textarea', rows: 2 },
      { id: 'riesgoHeteroagresivo', label: 'EVALUACIÓN DE RIESGO HETEROAGRESIVO', type: 'textarea', rows: 2 },
      { id: 'impresionDiagnostica', label: 'IMPRESIÓN DIAGNÓSTICA', type: 'textarea', required: true, rows: 2 },
      { id: 'medications', label: 'TRATAMIENTO FARMACOLÓGICO', type: 'medications' },
      { id: 'planTratamiento', label: 'PLAN DE TRATAMIENTO', type: 'textarea', rows: 3 },
      { id: 'control', label: 'CONTROL', type: 'input', required: true },
    ],
  },
  // NEUROLOGÍA
  {
    id: 'neurologia_general',
    name: 'Consulta Neurológica',
    description: 'Evaluación neurológica completa',
    category: 'neurologia',
    icon: 'Brain',
    color: 'purple',
    author: 'red-salud',
    tags: ['neurologia', 'sistema-nervioso', 'cerebro'],
    specialty: 'Neurología',
    fields: [
      { id: 'motivoConsulta', label: 'MOTIVO DE CONSULTA', type: 'textarea', required: true, rows: 2 },
      { id: 'historiaEnfermedad', label: 'HISTORIA DE LA ENFERMEDAD ACTUAL', type: 'textarea', required: true, rows: 4 },
      { id: 'antecedentes', label: 'ANTECEDENTES NEUROLÓGICOS', type: 'textarea', rows: 2 },
      { id: 'vitals', label: 'SIGNOS VITALES', type: 'vitals', required: true },
      { id: 'estadoMental', label: 'ESTADO MENTAL', type: 'textarea', required: true, rows: 2 },
      { id: 'paresCreaneales', label: 'PARES CRANEALES', type: 'textarea', required: true, rows: 3 },
      { id: 'motor', label: 'EXAMEN MOTOR', type: 'textarea', required: true, rows: 3 },
      { id: 'sensitivo', label: 'EXAMEN SENSITIVO', type: 'textarea', rows: 2 },
      { id: 'reflejos', label: 'REFLEJOS', type: 'textarea', rows: 2 },
      { id: 'coordinacion', label: 'COORDINACIÓN Y MARCHA', type: 'textarea', rows: 2 },
      { id: 'signosMeningeos', label: 'SIGNOS MENÍNGEOS', type: 'textarea', rows: 1 },
      { id: 'impresionDiagnostica', label: 'IMPRESIÓN DIAGNÓSTICA', type: 'textarea', required: true, rows: 2 },
      { id: 'medications', label: 'TRATAMIENTO', type: 'medications' },
      { id: 'planTratamiento', label: 'PLAN', type: 'textarea', rows: 3 },
      { id: 'control', label: 'CONTROL', type: 'input' },
    ],
  },
  // CARDIOLOGÍA
  {
    id: 'cardiologia_general',
    name: 'Consulta Cardiológica',
    description: 'Evaluación cardiológica completa',
    category: 'cardiologia',
    icon: 'Heart',
    color: 'red',
    author: 'red-salud',
    tags: ['cardiologia', 'corazon', 'cardiovascular'],
    specialty: 'Cardiología',
    fields: [
      { id: 'motivoConsulta', label: 'MOTIVO DE CONSULTA', type: 'textarea', required: true, rows: 2 },
      { id: 'sintomasCardiovasculares', label: 'SÍNTOMAS CARDIOVASCULARES', type: 'textarea', required: true, rows: 3 },
      { id: 'factoresRiesgo', label: 'FACTORES DE RIESGO CARDIOVASCULAR', type: 'textarea', rows: 3 },
      { id: 'antecedentes', label: 'ANTECEDENTES CARDIOVASCULARES', type: 'textarea', rows: 2 },
      { id: 'vitals', label: 'SIGNOS VITALES', type: 'vitals', required: true },
      { id: 'examenCardiovascular', label: 'EXAMEN CARDIOVASCULAR', type: 'textarea', required: true, rows: 4 },
      { id: 'ecg', label: 'ELECTROCARDIOGRAMA', type: 'textarea', rows: 3 },
      { id: 'ecocardiograma', label: 'ECOCARDIOGRAMA', type: 'textarea', rows: 3 },
      { id: 'laboratorios', label: 'LABORATORIOS', type: 'textarea', rows: 2 },
      { id: 'impresionDiagnostica', label: 'IMPRESIÓN DIAGNÓSTICA', type: 'textarea', required: true, rows: 2 },
      { id: 'medications', label: 'TRATAMIENTO', type: 'medications' },
      { id: 'recomendaciones', label: 'RECOMENDACIONES', type: 'textarea', rows: 3 },
      { id: 'control', label: 'CONTROL', type: 'input' },
    ],
  },
  // GASTROENTEROLOGÍA
  {
    id: 'gastroenterologia_general',
    name: 'Consulta Gastroenterológica',
    description: 'Evaluación gastroenterológica',
    category: 'especialidad',
    icon: 'Activity',
    color: 'yellow',
    author: 'red-salud',
    tags: ['gastroenterologia', 'digestivo', 'abdomen'],
    specialty: 'Gastroenterología',
    fields: [
      { id: 'motivoConsulta', label: 'MOTIVO DE CONSULTA', type: 'textarea', required: true, rows: 2 },
      { id: 'sintomasDigestivos', label: 'SÍNTOMAS DIGESTIVOS', type: 'textarea', required: true, rows: 3 },
      { id: 'habitosIntestinales', label: 'HÁBITOS INTESTINALES', type: 'textarea', rows: 2 },
      { id: 'dieta', label: 'DIETA', type: 'textarea', rows: 2 },
      { id: 'antecedentes', label: 'ANTECEDENTES GASTROINTESTINALES', type: 'textarea', rows: 2 },
      { id: 'vitals', label: 'SIGNOS VITALES', type: 'vitals', required: true },
      { id: 'examenAbdominal', label: 'EXAMEN ABDOMINAL', type: 'textarea', required: true, rows: 4 },
      { id: 'tactoRectal', label: 'TACTO RECTAL', type: 'textarea', rows: 2 },
      { id: 'laboratorios', label: 'LABORATORIOS', type: 'textarea', rows: 2 },
      { id: 'endoscopia', label: 'ENDOSCOPÍA', type: 'textarea', rows: 3 },
      { id: 'imagenologia', label: 'IMAGENOLOGÍA', type: 'textarea', rows: 2 },
      { id: 'impresionDiagnostica', label: 'IMPRESIÓN DIAGNÓSTICA', type: 'textarea', required: true, rows: 2 },
      { id: 'medications', label: 'TRATAMIENTO', type: 'medications' },
      { id: 'recomendaciones', label: 'RECOMENDACIONES DIETÉTICAS', type: 'textarea', rows: 3 },
      { id: 'control', label: 'CONTROL', type: 'input' },
    ],
  },
  // NEUMOLOGÍA
  {
    id: 'neumologia_general',
    name: 'Consulta Neumológica',
    description: 'Evaluación neumológica completa',
    category: 'especialidad',
    icon: 'Wind',
    color: 'sky',
    author: 'red-salud',
    tags: ['neumologia', 'respiratorio', 'pulmon'],
    specialty: 'Neumología',
    fields: [
      { id: 'motivoConsulta', label: 'MOTIVO DE CONSULTA', type: 'textarea', required: true, rows: 2 },
      { id: 'sintomasRespiratorios', label: 'SÍNTOMAS RESPIRATORIOS', type: 'textarea', required: true, rows: 3 },
      { id: 'tos', label: 'CARACTERÍSTICAS DE LA TOS', type: 'textarea', rows: 2 },
      { id: 'disnea', label: 'DISNEA', type: 'textarea', rows: 2 },
      { id: 'exposiciones', label: 'EXPOSICIONES AMBIENTALES/OCUPACIONALES', type: 'textarea', rows: 2 },
      { id: 'tabaquismo', label: 'TABAQUISMO', type: 'textarea', rows: 2 },
      { id: 'vitals', label: 'SIGNOS VITALES Y SATURACIÓN', type: 'vitals', required: true },
      { id: 'examenRespiratorio', label: 'EXAMEN RESPIRATORIO', type: 'textarea', required: true, rows: 4 },
      { id: 'espirometria', label: 'ESPIROMETRÍA', type: 'textarea', rows: 3 },
      { id: 'imagenologia', label: 'RADIOGRAFÍA/TAC DE TÓRAX', type: 'textarea', rows: 3 },
      { id: 'impresionDiagnostica', label: 'IMPRESIÓN DIAGNÓSTICA', type: 'textarea', required: true, rows: 2 },
      { id: 'medications', label: 'TRATAMIENTO', type: 'medications' },
      { id: 'recomendaciones', label: 'RECOMENDACIONES', type: 'textarea', rows: 3 },
      { id: 'control', label: 'CONTROL', type: 'input' },
    ],
  },
  // PROCEDIMIENTOS Y QUIRÚRGICOS
  {
    id: 'preoperatorio',
    name: 'Evaluación Preoperatoria',
    description: 'Evaluación médica preoperatoria',
    category: 'quirurgico',
    icon: 'Scissors',
    color: 'blue',
    author: 'red-salud',
    tags: ['preoperatorio', 'cirugia', 'evaluacion'],
    fields: [
      { id: 'procedimientoPropuesto', label: 'PROCEDIMIENTO QUIRÚRGICO PROPUESTO', type: 'textarea', required: true, rows: 2 },
      { id: 'antecedentesQuirurgicos', label: 'ANTECEDENTES QUIRÚRGICOS', type: 'textarea', rows: 2 },
      { id: 'antecedentesAnestesicos', label: 'ANTECEDENTES ANESTÉSICOS', type: 'textarea', rows: 2 },
      { id: 'comorbilidades', label: 'COMORBILIDADES', type: 'textarea', rows: 3 },
      { id: 'medicamentosActuales', label: 'MEDICAMENTOS ACTUALES', type: 'textarea', rows: 2 },
      { id: 'alergias', label: 'ALERGIAS', type: 'textarea', rows: 2 },
      { id: 'vitals', label: 'SIGNOS VITALES', type: 'vitals', required: true },
      { id: 'examenFisico', label: 'EXAMEN FÍSICO', type: 'textarea', required: true, rows: 3 },
      { id: 'viaAerea', label: 'EVALUACIÓN DE VÍA AÉREA', type: 'textarea', rows: 2 },
      { id: 'laboratorios', label: 'LABORATORIOS PREOPERATORIOS', type: 'textarea', rows: 3 },
      { id: 'ecg', label: 'ELECTROCARDIOGRAMA', type: 'textarea', rows: 2 },
      { id: 'imagenologia', label: 'IMAGENOLOGÍA', type: 'textarea', rows: 2 },
      { id: 'riesgoQuirurgico', label: 'EVALUACIÓN DE RIESGO QUIRÚRGICO', type: 'textarea', required: true, rows: 3 },
      { id: 'clasificacionASA', label: 'CLASIFICACIÓN ASA', type: 'input', required: true },
      { id: 'recomendaciones', label: 'RECOMENDACIONES PREOPERATORIAS', type: 'textarea', rows: 3 },
      { id: 'aptitud', label: 'APTITUD QUIRÚRGICA', type: 'textarea', required: true, rows: 2 },
    ],
  },
  {
    id: 'postoperatorio',
    name: 'Nota Postoperatoria',
    description: 'Evaluación postoperatoria inmediata',
    category: 'quirurgico',
    icon: 'ClipboardCheck',
    color: 'green',
    author: 'red-salud',
    tags: ['postoperatorio', 'cirugia', 'seguimiento'],
    fields: [
      { id: 'procedimientoRealizado', label: 'PROCEDIMIENTO REALIZADO', type: 'textarea', required: true, rows: 2 },
      { id: 'tiempoCirugia', label: 'TIEMPO DE CIRUGÍA', type: 'input' },
      { id: 'anestesia', label: 'TIPO DE ANESTESIA', type: 'input' },
      { id: 'hallazgos', label: 'HALLAZGOS QUIRÚRGICOS', type: 'textarea', required: true, rows: 3 },
      { id: 'complicaciones', label: 'COMPLICACIONES INTRAOPERATORIAS', type: 'textarea', rows: 2 },
      { id: 'vitals', label: 'SIGNOS VITALES', type: 'vitals', required: true },
      { id: 'dolor', label: 'EVALUACIÓN DEL DOLOR', type: 'textarea', rows: 2 },
      { id: 'herida', label: 'EVALUACIÓN DE HERIDA QUIRÚRGICA', type: 'textarea', rows: 2 },
      { id: 'drenajes', label: 'DRENAJES', type: 'textarea', rows: 1 },
      { id: 'diuresis', label: 'DIURESIS', type: 'input' },
      { id: 'toleranciaOral', label: 'TOLERANCIA ORAL', type: 'textarea', rows: 1 },
      { id: 'medications', label: 'MEDICAMENTOS POSTOPERATORIOS', type: 'medications' },
      { id: 'indicaciones', label: 'INDICACIONES', type: 'textarea', rows: 3 },
      { id: 'plan', label: 'PLAN', type: 'textarea', required: true, rows: 2 },
    ],
  },
  // MEDICINA INTERNA
  {
    id: 'medicina_interna',
    name: 'Consulta Medicina Interna',
    description: 'Evaluación de medicina interna',
    category: 'especialidad',
    icon: 'Stethoscope',
    color: 'indigo',
    author: 'red-salud',
    tags: ['medicina-interna', 'internista', 'complejo'],
    specialty: 'Medicina Interna',
    fields: [
      { id: 'motivoConsulta', label: 'MOTIVO DE CONSULTA', type: 'textarea', required: true, rows: 2 },
      { id: 'historiaEnfermedad', label: 'HISTORIA DE LA ENFERMEDAD ACTUAL', type: 'textarea', required: true, rows: 4 },
      { id: 'comorbilidades', label: 'COMORBILIDADES', type: 'textarea', rows: 3 },
      { id: 'medicamentosActuales', label: 'MEDICAMENTOS ACTUALES', type: 'textarea', rows: 3 },
      { id: 'revisionSistemas', label: 'REVISIÓN POR SISTEMAS', type: 'textarea', rows: 4 },
      { id: 'vitals', label: 'SIGNOS VITALES', type: 'vitals', required: true },
      { id: 'examenFisico', label: 'EXAMEN FÍSICO COMPLETO', type: 'textarea', required: true, rows: 5 },
      { id: 'laboratorios', label: 'LABORATORIOS', type: 'textarea', rows: 3 },
      { id: 'imagenologia', label: 'IMAGENOLOGÍA', type: 'textarea', rows: 2 },
      { id: 'impresionDiagnostica', label: 'IMPRESIÓN DIAGNÓSTICA', type: 'textarea', required: true, rows: 3 },
      { id: 'medications', label: 'TRATAMIENTO', type: 'medications' },
      { id: 'planTratamiento', label: 'PLAN DE MANEJO', type: 'textarea', rows: 4 },
      { id: 'control', label: 'CONTROL', type: 'input' },
    ],
  },
  // UROLOGÍA
  {
    id: 'urologia_general',
    name: 'Consulta Urológica',
    description: 'Evaluación urológica',
    category: 'especialidad',
    icon: 'Droplet',
    color: 'blue',
    author: 'red-salud',
    tags: ['urologia', 'genitourinario', 'prostata'],
    specialty: 'Urología',
    fields: [
      { id: 'motivoConsulta', label: 'MOTIVO DE CONSULTA', type: 'textarea', required: true, rows: 2 },
      { id: 'sintomasUrinarios', label: 'SÍNTOMAS URINARIOS', type: 'textarea', required: true, rows: 3 },
      { id: 'antecedentes', label: 'ANTECEDENTES UROLÓGICOS', type: 'textarea', rows: 2 },
      { id: 'vitals', label: 'SIGNOS VITALES', type: 'vitals', required: true },
      { id: 'examenAbdominal', label: 'EXAMEN ABDOMINAL', type: 'textarea', rows: 2 },
      { id: 'examenGenital', label: 'EXAMEN GENITAL', type: 'textarea', required: true, rows: 2 },
      { id: 'tactoRectal', label: 'TACTO RECTAL', type: 'textarea', rows: 2 },
      { id: 'laboratorios', label: 'LABORATORIOS (PSA, Urocultivo)', type: 'textarea', rows: 2 },
      { id: 'imagenologia', label: 'IMAGENOLOGÍA', type: 'textarea', rows: 2 },
      { id: 'impresionDiagnostica', label: 'IMPRESIÓN DIAGNÓSTICA', type: 'textarea', required: true, rows: 2 },
      { id: 'medications', label: 'TRATAMIENTO', type: 'medications' },
      { id: 'planTratamiento', label: 'PLAN', type: 'textarea', rows: 3 },
      { id: 'control', label: 'CONTROL', type: 'input' },
    ],
  },
  // ENDOCRINOLOGÍA
  {
    id: 'endocrinologia_general',
    name: 'Consulta Endocrinológica',
    description: 'Evaluación endocrinológica',
    category: 'especialidad',
    icon: 'Activity',
    color: 'purple',
    author: 'red-salud',
    tags: ['endocrinologia', 'hormonas', 'metabolismo'],
    specialty: 'Endocrinología',
    fields: [
      { id: 'motivoConsulta', label: 'MOTIVO DE CONSULTA', type: 'textarea', required: true, rows: 2 },
      { id: 'sintomas', label: 'SÍNTOMAS', type: 'textarea', required: true, rows: 3 },
      { id: 'antecedentes', label: 'ANTECEDENTES ENDOCRINOLÓGICOS', type: 'textarea', rows: 2 },
      { id: 'medicamentosActuales', label: 'MEDICAMENTOS ACTUALES', type: 'textarea', rows: 2 },
      { id: 'vitals', label: 'SIGNOS VITALES Y ANTROPOMETRÍA', type: 'vitals', required: true },
      { id: 'examenFisico', label: 'EXAMEN FÍSICO', type: 'textarea', required: true, rows: 3 },
      { id: 'examenTiroideo', label: 'EXAMEN TIROIDEO', type: 'textarea', rows: 2 },
      { id: 'laboratorios', label: 'LABORATORIOS HORMONALES', type: 'textarea', rows: 3 },
      { id: 'impresionDiagnostica', label: 'IMPRESIÓN DIAGNÓSTICA', type: 'textarea', required: true, rows: 2 },
      { id: 'medications', label: 'TRATAMIENTO', type: 'medications' },
      { id: 'recomendaciones', label: 'RECOMENDACIONES', type: 'textarea', rows: 3 },
      { id: 'control', label: 'CONTROL', type: 'input' },
    ],
  },
  // REUMATOLOGÍA
  {
    id: 'reumatologia_general',
    name: 'Consulta Reumatológica',
    description: 'Evaluación reumatológica',
    category: 'especialidad',
    icon: 'Bone',
    color: 'orange',
    author: 'red-salud',
    tags: ['reumatologia', 'articulaciones', 'autoinmune'],
    specialty: 'Reumatología',
    fields: [
      { id: 'motivoConsulta', label: 'MOTIVO DE CONSULTA', type: 'textarea', required: true, rows: 2 },
      { id: 'dolor', label: 'CARACTERÍSTICAS DEL DOLOR', type: 'textarea', required: true, rows: 3 },
      { id: 'rigidez', label: 'RIGIDEZ MATUTINA', type: 'textarea', rows: 2 },
      { id: 'articulacionesAfectadas', label: 'ARTICULACIONES AFECTADAS', type: 'textarea', required: true, rows: 2 },
      { id: 'manifestacionesExtraarticulares', label: 'MANIFESTACIONES EXTRAARTICULARES', type: 'textarea', rows: 2 },
      { id: 'vitals', label: 'SIGNOS VITALES', type: 'vitals', required: true },
      { id: 'examenArticular', label: 'EXAMEN ARTICULAR', type: 'textarea', required: true, rows: 4 },
      { id: 'movilidad', label: 'RANGOS DE MOVILIDAD', type: 'textarea', rows: 2 },
      { id: 'laboratorios', label: 'LABORATORIOS (FR, Anti-CCP, VSG, PCR)', type: 'textarea', rows: 3 },
      { id: 'imagenologia', label: 'IMAGENOLOGÍA', type: 'textarea', rows: 2 },
      { id: 'impresionDiagnostica', label: 'IMPRESIÓN DIAGNÓSTICA', type: 'textarea', required: true, rows: 2 },
      { id: 'medications', label: 'TRATAMIENTO', type: 'medications' },
      { id: 'recomendaciones', label: 'RECOMENDACIONES', type: 'textarea', rows: 3 },
      { id: 'control', label: 'CONTROL', type: 'input' },
    ],
  },
  // INFECTOLOGÍA
  {
    id: 'infectologia_general',
    name: 'Consulta Infectológica',
    description: 'Evaluación de enfermedades infecciosas',
    category: 'especialidad',
    icon: 'Bug',
    color: 'red',
    author: 'red-salud',
    tags: ['infectologia', 'infecciones', 'antibioticos'],
    specialty: 'Infectología',
    fields: [
      { id: 'motivoConsulta', label: 'MOTIVO DE CONSULTA', type: 'textarea', required: true, rows: 2 },
      { id: 'fiebre', label: 'CARACTERÍSTICAS DE LA FIEBRE', type: 'textarea', rows: 2 },
      { id: 'focoInfeccioso', label: 'FOCO INFECCIOSO SOSPECHADO', type: 'textarea', required: true, rows: 2 },
      { id: 'exposiciones', label: 'EXPOSICIONES Y VIAJES', type: 'textarea', rows: 2 },
      { id: 'antibioticosRecibidos', label: 'ANTIBIÓTICOS RECIBIDOS', type: 'textarea', rows: 2 },
      { id: 'vitals', label: 'SIGNOS VITALES', type: 'vitals', required: true },
      { id: 'examenFisico', label: 'EXAMEN FÍSICO', type: 'textarea', required: true, rows: 4 },
      { id: 'laboratorios', label: 'LABORATORIOS (Hemograma, PCR, Cultivos)', type: 'textarea', rows: 3 },
      { id: 'imagenologia', label: 'IMAGENOLOGÍA', type: 'textarea', rows: 2 },
      { id: 'impresionDiagnostica', label: 'IMPRESIÓN DIAGNÓSTICA', type: 'textarea', required: true, rows: 2 },
      { id: 'medications', label: 'TRATAMIENTO ANTIBIÓTICO', type: 'medications' },
      { id: 'planTratamiento', label: 'PLAN DE MANEJO', type: 'textarea', rows: 3 },
      { id: 'control', label: 'CONTROL', type: 'input' },
    ],
  },
  // SALUD MENTAL (Update)
  {
    id: 'evaluacion_salud_mental_completa',
    name: 'Evaluación Salud Mental Completa',
    description: 'Evaluación exhaustiva psicopatológica y psicosocial',
    category: 'psiquiatria',
    icon: 'Brain',
    color: 'indigo',
    author: 'red-salud',
    tags: ['salud-mental', 'psicologia', 'completo'],
    specialty: 'Psiquiatría',
    fields: [
      { id: 'header_general', label: 'Datos Generales', type: 'header', width: 'full' },
      { id: 'motivoConsulta', label: 'Motivo de Consulta', type: 'textarea', required: true, rows: 2, width: 'full' },
      { id: 'fuente_informacion', label: 'Fuente de Información', type: 'select', options: ['Paciente', 'Familiar', 'Remisión Médica', 'Otro'], width: 'half' },

      { id: 'header_antecedentes', label: 'Antecedentes', type: 'header', width: 'full' },
      { id: 'historia_familiar', label: 'Antecedentes Familiares', type: 'textarea', rows: 3, width: 'full', placeholder: 'Enfermedades mentales en la familia, suicidios, adicciones...' },
      { id: 'historia_personal', label: 'Historia Personal', type: 'textarea', rows: 3, width: 'full', placeholder: 'Desarrollo, infancia, educación, trabajo...' },

      { id: 'header_examen', label: 'Examen Mental', type: 'header', width: 'full' },
      { id: 'apariencia', label: 'Apariencia y Conducta', type: 'textarea', rows: 2, width: 'full' },
      { id: 'estado_animo', label: 'Estado de Ánimo', type: 'select', options: ['Eutímico', 'Depresivo', 'Maníaco', 'Ansioso', 'Irritable', 'Plano'], width: 'half' },
      { id: 'afecto', label: 'Afecto', type: 'select', options: ['Congruente', 'Incongruente', 'Restrigo', 'Embotado'], width: 'half' },
      { id: 'pensamiento', label: 'Pensamiento (Curso y Contenido)', type: 'textarea', rows: 2, width: 'full' },
      { id: 'senso_percepcion', label: 'Senso-percepción', type: 'select', options: ['Sin alteraciones', 'Alucinaciones Auditivas', 'Alucinaciones Visuales', 'Otras'], width: 'full' },
      { id: 'riesgo_suicida', label: 'Riesgo Suicida', type: 'radio', options: ['Sin Riesgo', 'Bajo', 'Moderado', 'Alto', 'Inminente'], width: 'full', required: true },

      { id: 'header_dx', label: 'Diagnóstico y Plan', type: 'header', width: 'full' },
      { id: 'impresion_dx', label: 'Impresión Diagnóstica (DSM-5 / CIE-11)', type: 'textarea', required: true, rows: 2, width: 'full' },
      { id: 'plan', label: 'Plan Terapéutico', type: 'textarea', required: true, rows: 3, width: 'full' },
    ],
  },
  // CARDIOLOGÍA AVANZADA
  {
    id: 'riesgo_cardiovascular',
    name: 'Evaluación Riesgo Cardiovascular',
    description: 'Score de riesgo y prevención primaria/secundaria',
    category: 'cardiologia',
    icon: 'Heart',
    color: 'red',
    author: 'red-salud',
    tags: ['cardiologia', 'riesgo', 'preventiva'],
    specialty: 'Cardiología',
    fields: [
      { id: 'info_paciente', label: 'Datos Básicos', type: 'header' },
      { id: 'edad', label: 'Edad', type: 'number', width: 'third', required: true },
      { id: 'genero', label: 'Género', type: 'select', options: ['Masculino', 'Femenino'], width: 'third', required: true },
      { id: 'tabaquismo', label: 'Tabaquismo', type: 'radio', options: ['No fuma', 'Ex-fumador', 'Fumador activo'], width: 'third', required: true },

      { id: 'info_clinica', label: 'Datos Clínicos', type: 'header' },
      { id: 'sistolica', label: 'PA Sistólica (mmHg)', type: 'number', width: 'half' },
      { id: 'colesterol_total', label: 'Colesterol Total (mg/dL)', type: 'number', width: 'half' },
      { id: 'hdl', label: 'Colesterol HDL (mg/dL)', type: 'number', width: 'half' },
      { id: 'diabetes', label: 'Diabetes', type: 'radio', options: ['No', 'Sí'], width: 'half' },

      { id: 'tratamiento', label: 'Tratamiento', type: 'header' },
      { id: 'htn_med', label: 'En tratamiento para Hipertensión', type: 'checkbox', options: ['Sí'], width: 'full' },
      { id: 'estatinas', label: 'En tratamiento con Estatinas', type: 'checkbox', options: ['Sí'], width: 'full' },

      { id: 'resultado', label: 'Cálculo de Riesgo (ASCVD)', type: 'textarea', width: 'full', helpText: 'Ingrese el porcentaje calculado y la categoría de riesgo' },
      { id: 'recomendaciones', label: 'Recomendaciones', type: 'textarea', rows: 4, width: 'full' },
    ]
  },
  // =====================================================
  // NUEVAS ESPECIALIDADES - NEFROLOGÍA
  // =====================================================
  {
    id: 'nefrologia_general',
    name: 'Consulta Nefrológica',
    description: 'Evaluación nefrológica completa',
    category: 'especialidad',
    icon: 'Droplet',
    color: 'blue',
    author: 'red-salud',
    tags: ['nefrologia', 'riñon', 'renal'],
    specialty: 'Nefrología',
    fields: [
      { id: 'motivoConsulta', label: 'MOTIVO DE CONSULTA', type: 'textarea', required: true, rows: 2 },
      { id: 'sintomasUrinarios', label: 'SÍNTOMAS URINARIOS', type: 'textarea', required: true, rows: 2 },
      { id: 'antecedentesRenales', label: 'ANTECEDENTES RENALES', type: 'textarea', rows: 2 },
      { id: 'medicamentosNefrotoxicos', label: 'EXPOSICIÓN A NEFROTÓXICOS', type: 'textarea', rows: 2 },
      { id: 'vitals', label: 'SIGNOS VITALES', type: 'vitals', required: true },
      { id: 'edemas', label: 'EVALUACIÓN DE EDEMAS', type: 'textarea', rows: 2 },
      { id: 'examenFisico', label: 'EXAMEN FÍSICO', type: 'textarea', required: true, rows: 3 },
      { id: 'laboratorios', label: 'LABORATORIOS (Creatinina, BUN, TFG)', type: 'textarea', rows: 3 },
      { id: 'urinalisis', label: 'URIANÁLISIS', type: 'textarea', rows: 2 },
      { id: 'imagenologia', label: 'IMAGENOLOGÍA RENAL', type: 'textarea', rows: 2 },
      { id: 'tfgCalculada', label: 'TFG CALCULADA', type: 'input' },
      { id: 'estadioERC', label: 'ESTADIO ERC', type: 'select', options: ['G1', 'G2', 'G3a', 'G3b', 'G4', 'G5', 'N/A'] },
      { id: 'impresionDiagnostica', label: 'IMPRESIÓN DIAGNÓSTICA', type: 'textarea', required: true, rows: 2 },
      { id: 'medications', label: 'TRATAMIENTO', type: 'medications' },
      { id: 'recomendaciones', label: 'RECOMENDACIONES', type: 'textarea', rows: 3 },
      { id: 'control', label: 'CONTROL', type: 'input' },
    ],
  },
  {
    id: 'control_erc',
    name: 'Control Enfermedad Renal Crónica',
    description: 'Seguimiento de paciente con ERC',
    category: 'control',
    icon: 'Droplet',
    color: 'blue',
    author: 'red-salud',
    tags: ['nefrologia', 'erc', 'cronico'],
    specialty: 'Nefrología',
    fields: [
      { id: 'motivoConsulta', label: 'MOTIVO', type: 'input', required: true },
      { id: 'evolucion', label: 'EVOLUCIÓN DESDE ÚLTIMA CONSULTA', type: 'textarea', required: true, rows: 2 },
      { id: 'sintomas', label: 'SÍNTOMAS URÉMICOS', type: 'textarea', rows: 2 },
      { id: 'diuresis', label: 'DIURESIS 24 HORAS', type: 'input' },
      { id: 'vitals', label: 'SIGNOS VITALES', type: 'vitals', required: true },
      { id: 'edemas', label: 'EDEMAS', type: 'textarea', rows: 1 },
      { id: 'laboratorios', label: 'LABORATORIOS', type: 'textarea', required: true, rows: 3 },
      { id: 'tfgActual', label: 'TFG ACTUAL', type: 'input', required: true },
      { id: 'estadioERC', label: 'ESTADIO ERC', type: 'select', options: ['G1', 'G2', 'G3a', 'G3b', 'G4', 'G5'], required: true },
      { id: 'evaluacion', label: 'EVALUACIÓN', type: 'textarea', required: true, rows: 2 },
      { id: 'medications', label: 'TRATAMIENTO', type: 'medications' },
      { id: 'dietaRenal', label: 'INDICACIONES DIETÉTICAS', type: 'textarea', rows: 2 },
      { id: 'recomendaciones', label: 'RECOMENDACIONES', type: 'textarea', rows: 2 },
      { id: 'control', label: 'PRÓXIMO CONTROL', type: 'input', required: true },
    ],
  },
  // =====================================================
  // HEMATOLOGÍA
  // =====================================================
  {
    id: 'hematologia_general',
    name: 'Consulta Hematológica',
    description: 'Evaluación hematológica completa',
    category: 'especialidad',
    icon: 'Droplet',
    color: 'red',
    author: 'red-salud',
    tags: ['hematologia', 'sangre', 'anemia'],
    specialty: 'Hematología',
    fields: [
      { id: 'motivoConsulta', label: 'MOTIVO DE CONSULTA', type: 'textarea', required: true, rows: 2 },
      { id: 'sintomas', label: 'SÍNTOMAS', type: 'textarea', required: true, rows: 3 },
      { id: 'sangrados', label: 'HISTORIA DE SANGRADOS', type: 'textarea', rows: 2 },
      { id: 'antecedentes', label: 'ANTECEDENTES HEMATOLÓGICOS', type: 'textarea', rows: 2 },
      { id: 'transfusiones', label: 'ANTECEDENTES DE TRANSFUSIONES', type: 'textarea', rows: 1 },
      { id: 'vitals', label: 'SIGNOS VITALES', type: 'vitals', required: true },
      { id: 'palidez', label: 'PALIDEZ/ICTERICIA', type: 'textarea', rows: 1 },
      { id: 'adenopatias', label: 'ADENOPATÍAS', type: 'textarea', rows: 2 },
      { id: 'hepatoesplenomegalia', label: 'HEPATOESPLENOMEGALIA', type: 'textarea', rows: 1 },
      { id: 'examenFisico', label: 'EXAMEN FÍSICO', type: 'textarea', required: true, rows: 3 },
      { id: 'hemograma', label: 'HEMOGRAMA COMPLETO', type: 'textarea', required: true, rows: 3 },
      { id: 'frotis', label: 'FROTIS DE SANGRE PERIFÉRICA', type: 'textarea', rows: 2 },
      { id: 'laboratoriosAdicionales', label: 'OTROS LABORATORIOS', type: 'textarea', rows: 2 },
      { id: 'impresionDiagnostica', label: 'IMPRESIÓN DIAGNÓSTICA', type: 'textarea', required: true, rows: 2 },
      { id: 'medications', label: 'TRATAMIENTO', type: 'medications' },
      { id: 'planTratamiento', label: 'PLAN', type: 'textarea', rows: 3 },
      { id: 'control', label: 'CONTROL', type: 'input' },
    ],
  },
  {
    id: 'evaluacion_anemia',
    name: 'Evaluación de Anemia',
    description: 'Evaluación sistemática de anemia',
    category: 'especialidad',
    icon: 'Droplet',
    color: 'red',
    author: 'red-salud',
    tags: ['hematologia', 'anemia', 'ferropenia'],
    specialty: 'Hematología',
    fields: [
      { id: 'motivoConsulta', label: 'MOTIVO', type: 'input', required: true },
      { id: 'sintomasAnemia', label: 'SÍNTOMAS DE ANEMIA', type: 'textarea', required: true, rows: 2 },
      { id: 'sangradoActivo', label: 'SANGRADO ACTIVO', type: 'textarea', rows: 2 },
      { id: 'dieta', label: 'HISTORIA DIETÉTICA', type: 'textarea', rows: 2 },
      { id: 'vitals', label: 'SIGNOS VITALES', type: 'vitals', required: true },
      { id: 'palidez', label: 'PALIDEZ CUTÁNEO-MUCOSA', type: 'textarea', rows: 1 },
      { id: 'hemograma', label: 'HEMOGRAMA', type: 'textarea', required: true, rows: 2 },
      { id: 'indicesEritrocitarios', label: 'ÍNDICES ERITROCITARIOS (VCM, HCM, CHCM)', type: 'textarea', rows: 2 },
      { id: 'perfilFerrico', label: 'PERFIL FÉRRICO', type: 'textarea', rows: 2 },
      { id: 'reticulocitos', label: 'RETICULOCITOS', type: 'input' },
      { id: 'tipoAnemia', label: 'CLASIFICACIÓN DE ANEMIA', type: 'select', options: ['Microcítica', 'Normocítica', 'Macrocítica'], required: true },
      { id: 'impresionDiagnostica', label: 'IMPRESIÓN DIAGNÓSTICA', type: 'textarea', required: true, rows: 2 },
      { id: 'medications', label: 'TRATAMIENTO', type: 'medications' },
      { id: 'recomendaciones', label: 'RECOMENDACIONES', type: 'textarea', rows: 2 },
      { id: 'control', label: 'CONTROL', type: 'input' },
    ],
  },
  {
    id: 'control_anticoagulacion',
    name: 'Control de Anticoagulación',
    description: 'Seguimiento de terapia anticoagulante',
    category: 'control',
    icon: 'Activity',
    color: 'red',
    author: 'red-salud',
    tags: ['hematologia', 'anticoagulacion', 'warfarina'],
    specialty: 'Hematología',
    fields: [
      { id: 'indicacionAnticoagulacion', label: 'INDICACIÓN DE ANTICOAGULACIÓN', type: 'input', required: true },
      { id: 'anticoagulanteActual', label: 'ANTICOAGULANTE ACTUAL Y DOSIS', type: 'input', required: true },
      { id: 'sangrados', label: 'EVENTOS DE SANGRADO', type: 'textarea', rows: 2 },
      { id: 'tromboticos', label: 'EVENTOS TROMBÓTICOS', type: 'textarea', rows: 1 },
      { id: 'adherencia', label: 'ADHERENCIA AL TRATAMIENTO', type: 'textarea', rows: 1 },
      { id: 'vitals', label: 'SIGNOS VITALES', type: 'vitals', required: true },
      { id: 'inr', label: 'INR ACTUAL', type: 'input', required: true },
      { id: 'rangoTerapeutico', label: 'RANGO TERAPÉUTICO OBJETIVO', type: 'input' },
      { id: 'tiempoEnRango', label: 'TIEMPO EN RANGO TERAPÉUTICO', type: 'input' },
      { id: 'interacciones', label: 'INTERACCIONES MEDICAMENTOSAS', type: 'textarea', rows: 2 },
      { id: 'evaluacion', label: 'EVALUACIÓN', type: 'textarea', required: true, rows: 2 },
      { id: 'ajusteDosis', label: 'AJUSTE DE DOSIS', type: 'textarea', rows: 2 },
      { id: 'medications', label: 'MEDICAMENTOS', type: 'medications' },
      { id: 'recomendaciones', label: 'RECOMENDACIONES', type: 'textarea', rows: 2 },
      { id: 'control', label: 'PRÓXIMO CONTROL', type: 'input', required: true },
    ],
  },
  // =====================================================
  // ONCOLOGÍA
  // =====================================================
  {
    id: 'oncologia_primera_vez',
    name: 'Primera Consulta Oncológica',
    description: 'Evaluación inicial de paciente oncológico',
    category: 'especialidad',
    icon: 'Activity',
    color: 'purple',
    author: 'red-salud',
    tags: ['oncologia', 'cancer', 'tumor'],
    specialty: 'Oncología',
    fields: [
      { id: 'motivoConsulta', label: 'MOTIVO DE CONSULTA', type: 'textarea', required: true, rows: 2 },
      { id: 'diagnosticoOncologico', label: 'DIAGNÓSTICO ONCOLÓGICO', type: 'textarea', required: true, rows: 2 },
      { id: 'histopatologia', label: 'REPORTE HISTOPATOLÓGICO', type: 'textarea', required: true, rows: 3 },
      { id: 'estadificacion', label: 'ESTADIFICACIÓN (TNM)', type: 'textarea', rows: 2 },
      { id: 'sintomas', label: 'SÍNTOMAS ACTUALES', type: 'textarea', rows: 2 },
      { id: 'antecedentes', label: 'ANTECEDENTES ONCOLÓGICOS FAMILIARES', type: 'textarea', rows: 2 },
      { id: 'vitals', label: 'SIGNOS VITALES', type: 'vitals', required: true },
      { id: 'ecog', label: 'ECOG PERFORMANCE STATUS', type: 'select', options: ['0', '1', '2', '3', '4'], required: true },
      { id: 'examenFisico', label: 'EXAMEN FÍSICO', type: 'textarea', required: true, rows: 3 },
      { id: 'laboratorios', label: 'LABORATORIOS', type: 'textarea', rows: 3 },
      { id: 'marcadoresTumorales', label: 'MARCADORES TUMORALES', type: 'textarea', rows: 2 },
      { id: 'imagenologia', label: 'IMAGENOLOGÍA', type: 'textarea', rows: 3 },
      { id: 'impresionDiagnostica', label: 'IMPRESIÓN DIAGNÓSTICA', type: 'textarea', required: true, rows: 2 },
      { id: 'planTratamiento', label: 'PLAN DE TRATAMIENTO PROPUESTO', type: 'textarea', required: true, rows: 4 },
      { id: 'pronostico', label: 'PRONÓSTICO', type: 'textarea', rows: 2 },
      { id: 'control', label: 'CONTROL', type: 'input' },
    ],
  },
  {
    id: 'control_oncologico',
    name: 'Control Oncológico',
    description: 'Seguimiento de paciente en tratamiento oncológico',
    category: 'control',
    icon: 'Activity',
    color: 'purple',
    author: 'red-salud',
    tags: ['oncologia', 'quimioterapia', 'seguimiento'],
    specialty: 'Oncología',
    fields: [
      { id: 'diagnosticoBase', label: 'DIAGNÓSTICO ONCOLÓGICO', type: 'input', required: true },
      { id: 'tratamientoActual', label: 'TRATAMIENTO ACTUAL', type: 'textarea', required: true, rows: 2 },
      { id: 'cicloActual', label: 'CICLO ACTUAL', type: 'input' },
      { id: 'sintomas', label: 'SÍNTOMAS', type: 'textarea', rows: 2 },
      { id: 'toxicidades', label: 'TOXICIDADES', type: 'textarea', required: true, rows: 3 },
      { id: 'vitals', label: 'SIGNOS VITALES', type: 'vitals', required: true },
      { id: 'ecog', label: 'ECOG', type: 'select', options: ['0', '1', '2', '3', '4'], required: true },
      { id: 'examenFisico', label: 'EXAMEN FÍSICO', type: 'textarea', rows: 2 },
      { id: 'laboratorios', label: 'LABORATORIOS', type: 'textarea', required: true, rows: 2 },
      { id: 'marcadores', label: 'MARCADORES TUMORALES', type: 'textarea', rows: 2 },
      { id: 'respuestaTratamiento', label: 'RESPUESTA AL TRATAMIENTO', type: 'select', options: ['Respuesta Completa', 'Respuesta Parcial', 'Enfermedad Estable', 'Progresión', 'No Evaluable'] },
      { id: 'evaluacion', label: 'EVALUACIÓN', type: 'textarea', required: true, rows: 2 },
      { id: 'medications', label: 'MEDICAMENTOS DE SOPORTE', type: 'medications' },
      { id: 'planTratamiento', label: 'PLAN', type: 'textarea', rows: 3 },
      { id: 'control', label: 'PRÓXIMO CONTROL', type: 'input', required: true },
    ],
  },
  // =====================================================
  // GERIATRÍA
  // =====================================================
  {
    id: 'geriatria_integral',
    name: 'Evaluación Geriátrica Integral',
    description: 'Evaluación multidimensional del adulto mayor',
    category: 'especialidad',
    icon: 'Heart',
    color: 'teal',
    author: 'red-salud',
    tags: ['geriatria', 'adulto-mayor', 'integral'],
    specialty: 'Geriatría',
    fields: [
      { id: 'motivoConsulta', label: 'MOTIVO DE CONSULTA', type: 'textarea', required: true, rows: 2 },
      { id: 'edad', label: 'EDAD', type: 'input', required: true },
      { id: 'cuidadorPrincipal', label: 'CUIDADOR PRINCIPAL', type: 'input' },
      { id: 'comorbilidades', label: 'COMORBILIDADES', type: 'textarea', rows: 3 },
      { id: 'medicamentos', label: 'LISTA DE MEDICAMENTOS', type: 'textarea', required: true, rows: 3 },
      { id: 'vitals', label: 'SIGNOS VITALES', type: 'vitals', required: true },
      { id: 'examenFisico', label: 'EXAMEN FÍSICO', type: 'textarea', rows: 3 },
      { id: 'estadoFuncional', label: 'ESTADO FUNCIONAL (AVD)', type: 'textarea', required: true, rows: 3, placeholder: 'Barthel, Lawton...' },
      { id: 'estadoCognitivo', label: 'ESTADO COGNITIVO', type: 'textarea', required: true, rows: 2, placeholder: 'MMSE, MoCA...' },
      { id: 'estadoAfectivo', label: 'ESTADO AFECTIVO', type: 'textarea', rows: 2, placeholder: 'GDS, PHQ-9...' },
      { id: 'estadoNutricional', label: 'ESTADO NUTRICIONAL', type: 'textarea', rows: 2, placeholder: 'MNA...' },
      { id: 'riesgosCaidas', label: 'RIESGO DE CAÍDAS', type: 'textarea', rows: 2 },
      { id: 'sindromes', label: 'SÍNDROMES GERIÁTRICOS IDENTIFICADOS', type: 'textarea', rows: 3 },
      { id: 'impresionDiagnostica', label: 'IMPRESIÓN DIAGNÓSTICA', type: 'textarea', required: true, rows: 2 },
      { id: 'medications', label: 'AJUSTE FARMACOLÓGICO', type: 'medications' },
      { id: 'planTratamiento', label: 'PLAN INTEGRAL', type: 'textarea', rows: 4 },
      { id: 'control', label: 'CONTROL', type: 'input' },
    ],
  },
  {
    id: 'evaluacion_caidas',
    name: 'Evaluación de Caídas',
    description: 'Evaluación de riesgo y post-caída en adulto mayor',
    category: 'especialidad',
    icon: 'AlertTriangle',
    color: 'orange',
    author: 'red-salud',
    tags: ['geriatria', 'caidas', 'riesgo'],
    specialty: 'Geriatría',
    fields: [
      { id: 'motivoConsulta', label: 'MOTIVO', type: 'input', required: true },
      { id: 'descripcionCaida', label: 'DESCRIPCIÓN DEL EVENTO', type: 'textarea', required: true, rows: 3 },
      { id: 'numerosCaidas', label: 'NÚMERO DE CAÍDAS ÚLTIMO AÑO', type: 'input' },
      { id: 'consecuencias', label: 'CONSECUENCIAS DE LA CAÍDA', type: 'textarea', rows: 2 },
      { id: 'factoresRiesgo', label: 'FACTORES DE RIESGO IDENTIFICADOS', type: 'textarea', required: true, rows: 3 },
      { id: 'medicamentosCaidas', label: 'MEDICAMENTOS QUE AUMENTAN RIESGO', type: 'textarea', rows: 2 },
      { id: 'vitals', label: 'SIGNOS VITALES', type: 'vitals', required: true },
      { id: 'ortostatismo', label: 'PRUEBA DE ORTOSTATISMO', type: 'textarea', rows: 2 },
      { id: 'examenNeurologico', label: 'EXAMEN NEUROLÓGICO', type: 'textarea', rows: 2 },
      { id: 'marcha', label: 'EVALUACIÓN DE MARCHA Y EQUILIBRIO', type: 'textarea', required: true, rows: 2 },
      { id: 'vision', label: 'EVALUACIÓN VISUAL', type: 'textarea', rows: 1 },
      { id: 'timedUpAndGo', label: 'TIMED UP AND GO', type: 'input' },
      { id: 'impresionDiagnostica', label: 'IMPRESIÓN DIAGNÓSTICA', type: 'textarea', required: true, rows: 2 },
      { id: 'medications', label: 'AJUSTE DE MEDICAMENTOS', type: 'medications' },
      { id: 'planPrevencion', label: 'PLAN DE PREVENCIÓN', type: 'textarea', rows: 3 },
      { id: 'control', label: 'CONTROL', type: 'input' },
    ],
  },
  // =====================================================
  // MEDICINA DEL DOLOR
  // =====================================================
  {
    id: 'dolor_cronico',
    name: 'Evaluación de Dolor Crónico',
    description: 'Evaluación integral del dolor crónico',
    category: 'especialidad',
    icon: 'Activity',
    color: 'red',
    author: 'red-salud',
    tags: ['dolor', 'cronico', 'analgesia'],
    specialty: 'Medicina del Dolor',
    fields: [
      { id: 'motivoConsulta', label: 'MOTIVO DE CONSULTA', type: 'textarea', required: true, rows: 2 },
      { id: 'localizacionDolor', label: 'LOCALIZACIÓN DEL DOLOR', type: 'textarea', required: true, rows: 2 },
      { id: 'caracteristicasDolor', label: 'CARACTERÍSTICAS (TIPO, IRRADIACIÓN)', type: 'textarea', required: true, rows: 2 },
      { id: 'intensidadDolor', label: 'INTENSIDAD (EVA 0-10)', type: 'input', required: true },
      { id: 'tiempoEvolucion', label: 'TIEMPO DE EVOLUCIÓN', type: 'input', required: true },
      { id: 'factoresModificadores', label: 'FACTORES ATENUANTES/AGRAVANTES', type: 'textarea', rows: 2 },
      { id: 'impactoFuncional', label: 'IMPACTO FUNCIONAL', type: 'textarea', rows: 2 },
      { id: 'tratamientosPrevios', label: 'TRATAMIENTOS PREVIOS', type: 'textarea', rows: 2 },
      { id: 'vitals', label: 'SIGNOS VITALES', type: 'vitals', required: true },
      { id: 'examenFisico', label: 'EXAMEN FÍSICO', type: 'textarea', required: true, rows: 3 },
      { id: 'examenNeurologico', label: 'EXAMEN NEUROLÓGICO', type: 'textarea', rows: 2 },
      { id: 'tipoDolor', label: 'TIPO DE DOLOR', type: 'select', options: ['Nociceptivo', 'Neuropático', 'Mixto', 'Nociplástico'], required: true },
      { id: 'impresionDiagnostica', label: 'IMPRESIÓN DIAGNÓSTICA', type: 'textarea', required: true, rows: 2 },
      { id: 'medications', label: 'TRATAMIENTO FARMACOLÓGICO', type: 'medications' },
      { id: 'planMultimodal', label: 'PLAN MULTIMODAL', type: 'textarea', rows: 3 },
      { id: 'control', label: 'CONTROL', type: 'input' },
    ],
  },
  // =====================================================
  // ALERGOLOGÍA
  // =====================================================
  {
    id: 'alergologia_general',
    name: 'Consulta de Alergología',
    description: 'Evaluación alergológica completa',
    category: 'especialidad',
    icon: 'Wind',
    color: 'green',
    author: 'red-salud',
    tags: ['alergologia', 'alergia', 'inmunologia'],
    specialty: 'Alergología',
    fields: [
      { id: 'motivoConsulta', label: 'MOTIVO DE CONSULTA', type: 'textarea', required: true, rows: 2 },
      { id: 'sintomasAlergicos', label: 'SÍNTOMAS ALÉRGICOS', type: 'textarea', required: true, rows: 3 },
      { id: 'desencadenantes', label: 'DESENCADENANTES IDENTIFICADOS', type: 'textarea', required: true, rows: 2 },
      { id: 'tiempoEvolucion', label: 'TIEMPO DE EVOLUCIÓN', type: 'input' },
      { id: 'estacionalidad', label: 'ESTACIONALIDAD', type: 'textarea', rows: 1 },
      { id: 'antecedentesAtopia', label: 'ANTECEDENTES DE ATOPIA', type: 'textarea', rows: 2 },
      { id: 'antecedentesFamiliares', label: 'ANTECEDENTES FAMILIARES', type: 'textarea', rows: 2 },
      { id: 'vitals', label: 'SIGNOS VITALES', type: 'vitals', required: true },
      { id: 'examenFisico', label: 'EXAMEN FÍSICO', type: 'textarea', required: true, rows: 3 },
      { id: 'pruebasCutaneas', label: 'PRUEBAS CUTÁNEAS', type: 'textarea', rows: 2 },
      { id: 'igeEspecifica', label: 'IgE ESPECÍFICA', type: 'textarea', rows: 2 },
      { id: 'impresionDiagnostica', label: 'IMPRESIÓN DIAGNÓSTICA', type: 'textarea', required: true, rows: 2 },
      { id: 'medications', label: 'TRATAMIENTO', type: 'medications' },
      { id: 'inmunoterapia', label: 'INDICACIÓN DE INMUNOTERAPIA', type: 'textarea', rows: 2 },
      { id: 'medidas', label: 'MEDIDAS DE EVITACIÓN', type: 'textarea', rows: 3 },
      { id: 'control', label: 'CONTROL', type: 'input' },
    ],
  },
  {
    id: 'asma_alergica',
    name: 'Evaluación de Asma Alérgica',
    description: 'Evaluación de asma bronquial alérgica',
    category: 'especialidad',
    icon: 'Wind',
    color: 'blue',
    author: 'red-salud',
    tags: ['alergologia', 'asma', 'respiratorio'],
    specialty: 'Alergología',
    fields: [
      { id: 'motivoConsulta', label: 'MOTIVO', type: 'input', required: true },
      { id: 'sintomasAsma', label: 'SÍNTOMAS DE ASMA', type: 'textarea', required: true, rows: 2 },
      { id: 'frecuenciaSintomas', label: 'FRECUENCIA DE SÍNTOMAS', type: 'textarea', rows: 2 },
      { id: 'despertaresNocturnos', label: 'DESPERTARES NOCTURNOS', type: 'input' },
      { id: 'usoRescate', label: 'USO DE MEDICACIÓN DE RESCATE', type: 'input' },
      { id: 'limitacionActividades', label: 'LIMITACIÓN DE ACTIVIDADES', type: 'textarea', rows: 1 },
      { id: 'desencadenantes', label: 'DESENCADENANTES', type: 'textarea', rows: 2 },
      { id: 'vitals', label: 'SIGNOS VITALES Y SATURACIÓN', type: 'vitals', required: true },
      { id: 'examenRespiratorio', label: 'EXAMEN RESPIRATORIO', type: 'textarea', required: true, rows: 2 },
      { id: 'peakFlow', label: 'PEAK FLOW', type: 'input' },
      { id: 'espirometria', label: 'ESPIROMETRÍA', type: 'textarea', rows: 2 },
      { id: 'controlAsma', label: 'NIVEL DE CONTROL', type: 'select', options: ['Controlada', 'Parcialmente Controlada', 'No Controlada'], required: true },
      { id: 'severidad', label: 'SEVERIDAD', type: 'select', options: ['Intermitente', 'Leve Persistente', 'Moderada Persistente', 'Severa Persistente'] },
      { id: 'impresionDiagnostica', label: 'IMPRESIÓN DIAGNÓSTICA', type: 'textarea', required: true, rows: 2 },
      { id: 'medications', label: 'TRATAMIENTO', type: 'medications' },
      { id: 'planAccion', label: 'PLAN DE ACCIÓN', type: 'textarea', rows: 3 },
      { id: 'control', label: 'CONTROL', type: 'input' },
    ],
  },
  // =====================================================
  // NUTRICIÓN
  // =====================================================
  {
    id: 'evaluacion_nutricional',
    name: 'Evaluación Nutricional',
    description: 'Evaluación nutricional completa',
    category: 'especialidad',
    icon: 'Apple',
    color: 'green',
    author: 'red-salud',
    tags: ['nutricion', 'dieta', 'peso'],
    specialty: 'Nutrición',
    fields: [
      { id: 'motivoConsulta', label: 'MOTIVO DE CONSULTA', type: 'textarea', required: true, rows: 2 },
      { id: 'objetivoNutricional', label: 'OBJETIVO NUTRICIONAL', type: 'textarea', rows: 2 },
      { id: 'antecedentesPatologicos', label: 'ANTECEDENTES PATOLÓGICOS', type: 'textarea', rows: 2 },
      { id: 'historiaDietetica', label: 'HISTORIA DIETÉTICA', type: 'textarea', required: true, rows: 3 },
      { id: 'recordatorio24h', label: 'RECORDATORIO 24 HORAS', type: 'textarea', rows: 3 },
      { id: 'alergias', label: 'ALERGIAS/INTOLERANCIAS ALIMENTARIAS', type: 'textarea', rows: 2 },
      { id: 'actividadFisica', label: 'ACTIVIDAD FÍSICA', type: 'textarea', rows: 2 },
      { id: 'antropometria', label: 'ANTROPOMETRÍA', type: 'vitals', required: true },
      { id: 'imc', label: 'IMC', type: 'input', required: true },
      { id: 'circunferenciaCintura', label: 'CIRCUNFERENCIA DE CINTURA', type: 'input' },
      { id: 'composicionCorporal', label: 'COMPOSICIÓN CORPORAL', type: 'textarea', rows: 2 },
      { id: 'laboratorios', label: 'LABORATORIOS NUTRICIONALES', type: 'textarea', rows: 2 },
      { id: 'diagnosticoNutricional', label: 'DIAGNÓSTICO NUTRICIONAL', type: 'textarea', required: true, rows: 2 },
      { id: 'requerimientoCalorico', label: 'REQUERIMIENTO CALÓRICO', type: 'input' },
      { id: 'planAlimentacion', label: 'PLAN DE ALIMENTACIÓN', type: 'textarea', required: true, rows: 4 },
      { id: 'recomendaciones', label: 'RECOMENDACIONES', type: 'textarea', rows: 3 },
      { id: 'control', label: 'CONTROL', type: 'input' },
    ],
  },
  // =====================================================
  // REHABILITACIÓN
  // =====================================================
  {
    id: 'rehabilitacion_general',
    name: 'Evaluación de Rehabilitación',
    description: 'Evaluación fisiatrica integral',
    category: 'especialidad',
    icon: 'Activity',
    color: 'teal',
    author: 'red-salud',
    tags: ['rehabilitacion', 'fisiatria', 'terapia'],
    specialty: 'Fisiatría',
    fields: [
      { id: 'motivoConsulta', label: 'MOTIVO DE CONSULTA', type: 'textarea', required: true, rows: 2 },
      { id: 'diagnosticoBase', label: 'DIAGNÓSTICO DE BASE', type: 'textarea', required: true, rows: 2 },
      { id: 'tiempoEvolucion', label: 'TIEMPO DE EVOLUCIÓN', type: 'input' },
      { id: 'limitacionesFuncionales', label: 'LIMITACIONES FUNCIONALES', type: 'textarea', required: true, rows: 3 },
      { id: 'tratamientosPrevios', label: 'TRATAMIENTOS DE REHABILITACIÓN PREVIOS', type: 'textarea', rows: 2 },
      { id: 'objetivosRehabilitacion', label: 'OBJETIVOS DE REHABILITACIÓN', type: 'textarea', rows: 2 },
      { id: 'vitals', label: 'SIGNOS VITALES', type: 'vitals', required: true },
      { id: 'examenMusculoesqueletico', label: 'EXAMEN MUSCULOESQUELÉTICO', type: 'textarea', required: true, rows: 3 },
      { id: 'fuerzaMuscular', label: 'FUERZA MUSCULAR', type: 'textarea', rows: 2 },
      { id: 'rangosMovilidad', label: 'RANGOS DE MOVILIDAD', type: 'textarea', rows: 2 },
      { id: 'marcha', label: 'EVALUACIÓN DE MARCHA', type: 'textarea', rows: 2 },
      { id: 'evaluacionFuncional', label: 'EVALUACIÓN FUNCIONAL', type: 'textarea', required: true, rows: 2 },
      { id: 'impresionDiagnostica', label: 'IMPRESIÓN DIAGNÓSTICA', type: 'textarea', required: true, rows: 2 },
      { id: 'planRehabilitacion', label: 'PLAN DE REHABILITACIÓN', type: 'textarea', required: true, rows: 4 },
      { id: 'medications', label: 'MEDICAMENTOS', type: 'medications' },
      { id: 'control', label: 'CONTROL', type: 'input' },
    ],
  },
  // =====================================================
  // TEMPLATES ADICIONALES - PEDIATRÍA
  // =====================================================
  {
    id: 'pediatria_fiebre',
    name: 'Fiebre en Pediatría',
    description: 'Evaluación de síndrome febril en niños',
    category: 'pediatria',
    icon: 'Thermometer',
    color: 'red',
    author: 'red-salud',
    tags: ['pediatria', 'fiebre', 'infeccion'],
    specialty: 'Pediatría',
    fields: [
      { id: 'edad', label: 'EDAD', type: 'input', required: true },
      { id: 'motivoConsulta', label: 'MOTIVO', type: 'input', required: true },
      { id: 'tiempoFiebre', label: 'TIEMPO DE EVOLUCIÓN DE FIEBRE', type: 'input', required: true },
      { id: 'temperaturaMaxima', label: 'TEMPERATURA MÁXIMA', type: 'input' },
      { id: 'sintomasAsociados', label: 'SÍNTOMAS ASOCIADOS', type: 'textarea', required: true, rows: 3 },
      { id: 'contactoEnfermos', label: 'CONTACTO CON ENFERMOS', type: 'textarea', rows: 1 },
      { id: 'vacunacion', label: 'ESTADO DE VACUNACIÓN', type: 'textarea', rows: 2 },
      { id: 'vitals', label: 'SIGNOS VITALES', type: 'vitals', required: true },
      { id: 'estadoGeneral', label: 'ESTADO GENERAL', type: 'textarea', required: true, rows: 2 },
      { id: 'examenFisico', label: 'EXAMEN FÍSICO POR SISTEMAS', type: 'textarea', required: true, rows: 4 },
      { id: 'focoInfeccioso', label: 'FOCO INFECCIOSO IDENTIFICADO', type: 'textarea', rows: 2 },
      { id: 'laboratorios', label: 'LABORATORIOS', type: 'textarea', rows: 2 },
      { id: 'impresionDiagnostica', label: 'IMPRESIÓN DIAGNÓSTICA', type: 'textarea', required: true, rows: 2 },
      { id: 'medications', label: 'TRATAMIENTO', type: 'medications' },
      { id: 'signosAlarma', label: 'SIGNOS DE ALARMA', type: 'textarea', rows: 2 },
      { id: 'control', label: 'CONTROL', type: 'input' },
    ],
  },
  {
    id: 'ira_pediatrica',
    name: 'Infección Respiratoria Pediátrica',
    description: 'Evaluación de IRA en niños',
    category: 'pediatria',
    icon: 'Wind',
    color: 'blue',
    author: 'red-salud',
    tags: ['pediatria', 'respiratorio', 'ira'],
    specialty: 'Pediatría',
    fields: [
      { id: 'edad', label: 'EDAD', type: 'input', required: true },
      { id: 'motivoConsulta', label: 'MOTIVO', type: 'input', required: true },
      { id: 'sintomasRespiratorios', label: 'SÍNTOMAS RESPIRATORIOS', type: 'textarea', required: true, rows: 2 },
      { id: 'tiempoEvolucion', label: 'TIEMPO DE EVOLUCIÓN', type: 'input', required: true },
      { id: 'fiebre', label: 'FIEBRE', type: 'textarea', rows: 1 },
      { id: 'alimentacion', label: 'ALIMENTACIÓN', type: 'textarea', rows: 1 },
      { id: 'vitals', label: 'SIGNOS VITALES Y SATURACIÓN', type: 'vitals', required: true },
      { id: 'dificultadRespiratoria', label: 'SIGNOS DE DIFICULTAD RESPIRATORIA', type: 'textarea', required: true, rows: 2 },
      { id: 'examenRespiratorio', label: 'EXAMEN RESPIRATORIO', type: 'textarea', required: true, rows: 3 },
      { id: 'examenORL', label: 'EXAMEN ORL', type: 'textarea', rows: 2 },
      { id: 'clasificacion', label: 'CLASIFICACIÓN AIEPI', type: 'select', options: ['Neumonía Grave', 'Neumonía', 'No Neumonía: Tos/Resfriado'] },
      { id: 'impresionDiagnostica', label: 'IMPRESIÓN DIAGNÓSTICA', type: 'textarea', required: true, rows: 2 },
      { id: 'medications', label: 'TRATAMIENTO', type: 'medications' },
      { id: 'signosAlarma', label: 'SIGNOS DE ALARMA', type: 'textarea', rows: 2 },
      { id: 'control', label: 'CONTROL', type: 'input' },
    ],
  },
  // =====================================================
  // TEMPLATES ADICIONALES - GINECOLOGÍA
  // =====================================================
  {
    id: 'control_postparto',
    name: 'Control Postparto',
    description: 'Seguimiento puerperal',
    category: 'ginecologia',
    icon: 'Baby',
    color: 'pink',
    author: 'red-salud',
    tags: ['ginecologia', 'postparto', 'puerperio'],
    specialty: 'Obstetricia',
    fields: [
      { id: 'tiposParto', label: 'TIPO DE PARTO', type: 'select', options: ['Vaginal', 'Cesárea', 'Instrumentado'], required: true },
      { id: 'fechaParto', label: 'FECHA DE PARTO', type: 'date', required: true },
      { id: 'diasPostparto', label: 'DÍAS POSTPARTO', type: 'input', required: true },
      { id: 'sintomas', label: 'SÍNTOMAS', type: 'textarea', rows: 2 },
      { id: 'sangrado', label: 'SANGRADO VAGINAL', type: 'textarea', rows: 2 },
      { id: 'lactancia', label: 'LACTANCIA MATERNA', type: 'textarea', rows: 2 },
      { id: 'estadoEmocional', label: 'ESTADO EMOCIONAL', type: 'textarea', rows: 2 },
      { id: 'vitals', label: 'SIGNOS VITALES', type: 'vitals', required: true },
      { id: 'mamas', label: 'EXAMEN DE MAMAS', type: 'textarea', required: true, rows: 2 },
      { id: 'involucionUterina', label: 'INVOLUCIÓN UTERINA', type: 'textarea', rows: 2 },
      { id: 'heridaQuirurgica', label: 'HERIDA QUIRÚRGICA/EPISIORRAFIA', type: 'textarea', rows: 2 },
      { id: 'loquios', label: 'LOQUIOS', type: 'textarea', rows: 1 },
      { id: 'evaluacion', label: 'EVALUACIÓN', type: 'textarea', required: true, rows: 2 },
      { id: 'medications', label: 'MEDICAMENTOS', type: 'medications' },
      { id: 'anticoncepcion', label: 'ANTICONCEPCIÓN', type: 'textarea', rows: 2 },
      { id: 'recomendaciones', label: 'RECOMENDACIONES', type: 'textarea', rows: 2 },
      { id: 'control', label: 'PRÓXIMO CONTROL', type: 'input' },
    ],
  },
  {
    id: 'evaluacion_menopausia',
    name: 'Evaluación de Menopausia',
    description: 'Evaluación de síndrome climatérico',
    category: 'ginecologia',
    icon: 'Heart',
    color: 'purple',
    author: 'red-salud',
    tags: ['ginecologia', 'menopausia', 'climaterio'],
    specialty: 'Ginecología',
    fields: [
      { id: 'motivoConsulta', label: 'MOTIVO DE CONSULTA', type: 'textarea', required: true, rows: 2 },
      { id: 'fur', label: 'FECHA ÚLTIMA REGLA', type: 'date' },
      { id: 'tiempoAmenorrea', label: 'TIEMPO DE AMENORREA', type: 'input' },
      { id: 'sintomasVasomotores', label: 'SÍNTOMAS VASOMOTORES', type: 'textarea', required: true, rows: 2 },
      { id: 'sintomasUrogenitales', label: 'SÍNTOMAS UROGENITALES', type: 'textarea', rows: 2 },
      { id: 'alteracionesSueño', label: 'ALTERACIONES DEL SUEÑO', type: 'textarea', rows: 1 },
      { id: 'estadoAnimo', label: 'ESTADO DE ÁNIMO', type: 'textarea', rows: 1 },
      { id: 'antecedentesGinecologicos', label: 'ANTECEDENTES GINECOLÓGICOS', type: 'textarea', rows: 2 },
      { id: 'factoresRiesgo', label: 'FACTORES DE RIESGO CARDIOVASCULAR', type: 'textarea', rows: 2 },
      { id: 'vitals', label: 'SIGNOS VITALES', type: 'vitals', required: true },
      { id: 'examenGinecologico', label: 'EXAMEN GINECOLÓGICO', type: 'textarea', rows: 2 },
      { id: 'examenMamas', label: 'EXAMEN DE MAMAS', type: 'textarea', rows: 2 },
      { id: 'laboratorios', label: 'LABORATORIOS (FSH, Estradiol, Perfil Lipídico)', type: 'textarea', rows: 2 },
      { id: 'densitometria', label: 'DENSITOMETRÍA ÓSEA', type: 'textarea', rows: 2 },
      { id: 'impresionDiagnostica', label: 'IMPRESIÓN DIAGNÓSTICA', type: 'textarea', required: true, rows: 2 },
      { id: 'medications', label: 'TRATAMIENTO', type: 'medications' },
      { id: 'recomendaciones', label: 'RECOMENDACIONES', type: 'textarea', rows: 3 },
      { id: 'control', label: 'CONTROL', type: 'input' },
    ],
  },
  // =====================================================
  // TEMPLATES ADICIONALES - CARDIOLOGÍA
  // =====================================================
  {
    id: 'insuficiencia_cardiaca',
    name: 'Insuficiencia Cardíaca',
    description: 'Evaluación y seguimiento de IC',
    category: 'cardiologia',
    icon: 'Heart',
    color: 'red',
    author: 'red-salud',
    tags: ['cardiologia', 'insuficiencia-cardiaca', 'fevi'],
    specialty: 'Cardiología',
    fields: [
      { id: 'motivoConsulta', label: 'MOTIVO DE CONSULTA', type: 'textarea', required: true, rows: 2 },
      { id: 'clasificacionNYHA', label: 'CLASE FUNCIONAL NYHA', type: 'select', options: ['I', 'II', 'III', 'IV'], required: true },
      { id: 'disnea', label: 'DISNEA', type: 'textarea', rows: 2 },
      { id: 'ortopnea', label: 'ORTOPNEA/DPN', type: 'textarea', rows: 1 },
      { id: 'edemas', label: 'EDEMAS', type: 'textarea', rows: 2 },
      { id: 'pesoGanancia', label: 'CAMBIOS DE PESO', type: 'input' },
      { id: 'adherencia', label: 'ADHERENCIA A TRATAMIENTO', type: 'textarea', rows: 2 },
      { id: 'vitals', label: 'SIGNOS VITALES', type: 'vitals', required: true },
      { id: 'ingurgitacionYugular', label: 'INGURGITACIÓN YUGULAR', type: 'textarea', rows: 1 },
      { id: 'examenCardiaco', label: 'EXAMEN CARDÍACO', type: 'textarea', required: true, rows: 3 },
      { id: 'examenPulmonar', label: 'EXAMEN PULMONAR', type: 'textarea', rows: 2 },
      { id: 'laboratorios', label: 'LABORATORIOS (BNP/NT-proBNP)', type: 'textarea', rows: 2 },
      { id: 'fevi', label: 'FEVI', type: 'input' },
      { id: 'tipoIC', label: 'TIPO DE IC', type: 'select', options: ['ICFEr', 'ICFEm', 'ICFEp'] },
      { id: 'evaluacion', label: 'EVALUACIÓN', type: 'textarea', required: true, rows: 2 },
      { id: 'medications', label: 'TRATAMIENTO', type: 'medications' },
      { id: 'recomendaciones', label: 'RECOMENDACIONES', type: 'textarea', rows: 3 },
      { id: 'control', label: 'CONTROL', type: 'input' },
    ],
  },
  // =====================================================
  // TEMPLATES ADICIONALES - EMERGENCIAS
  // =====================================================
  {
    id: 'crisis_hipertensiva',
    name: 'Crisis Hipertensiva',
    description: 'Evaluación de emergencia/urgencia hipertensiva',
    category: 'emergencia',
    icon: 'AlertCircle',
    color: 'red',
    author: 'red-salud',
    tags: ['emergencia', 'hipertension', 'crisis'],
    fields: [
      { id: 'motivoConsulta', label: 'MOTIVO', type: 'input', required: true },
      { id: 'presionArterial', label: 'PRESIÓN ARTERIAL INICIAL', type: 'input', required: true },
      { id: 'sintomasAsociados', label: 'SÍNTOMAS ASOCIADOS', type: 'textarea', required: true, rows: 3 },
      { id: 'dañoOrganoDiana', label: 'EVIDENCIA DE DAÑO A ÓRGANO DIANA', type: 'textarea', required: true, rows: 2 },
      { id: 'antecedentesHTA', label: 'ANTECEDENTES DE HTA', type: 'textarea', rows: 2 },
      { id: 'medicamentosActuales', label: 'MEDICAMENTOS ACTUALES', type: 'textarea', rows: 2 },
      { id: 'adherencia', label: 'ADHERENCIA AL TRATAMIENTO', type: 'textarea', rows: 1 },
      { id: 'vitals', label: 'SIGNOS VITALES', type: 'vitals', required: true },
      { id: 'examenNeurologico', label: 'EXAMEN NEUROLÓGICO', type: 'textarea', required: true, rows: 2 },
      { id: 'examenCardiaco', label: 'EXAMEN CARDIOVASCULAR', type: 'textarea', rows: 2 },
      { id: 'fondoOjo', label: 'FONDO DE OJO', type: 'textarea', rows: 1 },
      { id: 'ecg', label: 'ELECTROCARDIOGRAMA', type: 'textarea', rows: 2 },
      { id: 'laboratorios', label: 'LABORATORIOS', type: 'textarea', rows: 2 },
      { id: 'tipoCrisis', label: 'TIPO DE CRISIS', type: 'select', options: ['Urgencia Hipertensiva', 'Emergencia Hipertensiva'], required: true },
      { id: 'impresionDiagnostica', label: 'IMPRESIÓN DIAGNÓSTICA', type: 'textarea', required: true, rows: 2 },
      { id: 'medications', label: 'TRATAMIENTO', type: 'medications' },
      { id: 'conducta', label: 'CONDUCTA', type: 'textarea', required: true, rows: 3 },
    ],
  },
  {
    id: 'intoxicacion_aguda',
    name: 'Intoxicación Aguda',
    description: 'Evaluación de intoxicación en emergencia',
    category: 'emergencia',
    icon: 'AlertTriangle',
    color: 'orange',
    author: 'red-salud',
    tags: ['emergencia', 'intoxicacion', 'toxicologia'],
    fields: [
      { id: 'motivoConsulta', label: 'MOTIVO', type: 'input', required: true },
      { id: 'agenteToxico', label: 'AGENTE TÓXICO', type: 'textarea', required: true, rows: 2 },
      { id: 'viaExposicion', label: 'VÍA DE EXPOSICIÓN', type: 'select', options: ['Oral', 'Inhalación', 'Cutánea', 'Ocular', 'Parenteral'], required: true },
      { id: 'cantidadExpuesta', label: 'CANTIDAD EXPUESTA', type: 'input' },
      { id: 'tiempoExposicion', label: 'TIEMPO DESDE EXPOSICIÓN', type: 'input', required: true },
      { id: 'intencion', label: 'INTENCIÓN', type: 'select', options: ['Accidental', 'Suicida', 'Homicida', 'Ocupacional', 'Recreacional'], required: true },
      { id: 'sintomas', label: 'SÍNTOMAS', type: 'textarea', required: true, rows: 2 },
      { id: 'vitals', label: 'SIGNOS VITALES', type: 'vitals', required: true },
      { id: 'glasgow', label: 'ESCALA DE GLASGOW', type: 'input', required: true },
      { id: 'pupilas', label: 'PUPILAS (TAMAÑO, REACTIVIDAD)', type: 'input' },
      { id: 'examenFisico', label: 'EXAMEN FÍSICO', type: 'textarea', required: true, rows: 3 },
      { id: 'toxindrome', label: 'TOXÍNDROME IDENTIFICADO', type: 'select', options: ['Colinérgico', 'Anticolinérgico', 'Simpaticomimético', 'Opiáceo', 'Sedante-Hipnótico', 'Serotoninérgico', 'Ninguno Específico'] },
      { id: 'laboratorios', label: 'LABORATORIOS Y TOXICOLOGÍA', type: 'textarea', rows: 2 },
      { id: 'impresionDiagnostica', label: 'IMPRESIÓN DIAGNÓSTICA', type: 'textarea', required: true, rows: 2 },
      { id: 'descontaminacion', label: 'DESCONTAMINACIÓN REALIZADA', type: 'textarea', rows: 2 },
      { id: 'antidoto', label: 'ANTÍDOTO', type: 'textarea', rows: 1 },
      { id: 'medications', label: 'TRATAMIENTO', type: 'medications' },
      { id: 'conducta', label: 'CONDUCTA', type: 'textarea', required: true, rows: 3 },
    ],
  },
];

// Función para obtener todos los templates (originales + extendidos)
export function getAllTemplates(): StructuredTemplate[] {
  return EXTENDED_TEMPLATES;
}

// Función para obtener templates por categoría
export function getTemplatesByCategory(category: string): StructuredTemplate[] {
  if (category === 'all') return EXTENDED_TEMPLATES;
  return EXTENDED_TEMPLATES.filter(t => t.category === category);
}

// Función para obtener templates por especialidad
export function getTemplatesBySpecialty(specialty: string): StructuredTemplate[] {
  return EXTENDED_TEMPLATES.filter(t => t.specialty === specialty);
}

// Función para buscar templates
export function searchTemplates(query: string): StructuredTemplate[] {
  const lowerQuery = query.toLowerCase();
  return EXTENDED_TEMPLATES.filter(t =>
    t.name.toLowerCase().includes(lowerQuery) ||
    t.description.toLowerCase().includes(lowerQuery) ||
    t.tags.some(tag => tag.toLowerCase().includes(lowerQuery)) ||
    (t.specialty && t.specialty.toLowerCase().includes(lowerQuery))
  );
}
