// Sugerencias médicas comunes para autocompletado

export const ALERGIAS_MEDICAMENTOS = [
  "Penicilina",
  "Amoxicilina",
  "Ampicilina",
  "Cefalosporinas",
  "Ceftriaxona",
  "Cefalexina",
  "Sulfonamidas",
  "Trimetoprim-sulfametoxazol",
  "Aspirina (AAS)",
  "Ibuprofeno",
  "Naproxeno",
  "Diclofenaco",
  "Paracetamol",
  "Codeína",
  "Morfina",
  "Tramadol",
  "Anestésicos locales",
  "Lidocaína",
  "Procaína",
  "Insulina",
  "Contrastes yodados",
  "Látex",
  "Quinolonas",
  "Ciprofloxacino",
  "Macrólidos",
  "Azitromicina",
  "Eritromicina",
  "Metronidazol",
  "Vancomicina",
  "Gentamicina",
  "Warfarina",
  "Heparina",
  "Estatinas",
  "Atorvastatina",
  "Simvastatina",
  "Metformina",
  "Insulina glargina",
  "Omeprazol",
  "Ranitidina",
  "Prednisona",
  "Dexametasona",
  "Fenitoína",
  "Carbamazepina",
  "Ácido valproico",
  "Propofol",
  "Ketamina",
  "Midazolam",
];

export const ALERGIAS_ALIMENTARIAS = [
  "Mariscos",
  "Camarones",
  "Cangrejo",
  "Langosta",
  "Pescado",
  "Salmón",
  "Atún",
  "Leche",
  "Lactosa",
  "Caseína",
  "Huevos",
  "Maní (cacahuate)",
  "Nueces",
  "Almendras",
  "Avellanas",
  "Pistachos",
  "Anacardos",
  "Soja",
  "Trigo",
  "Gluten",
  "Fructosa",
  "Apio",
  "Mostaza",
  "Sésamo",
  "Sulfitos",
  "Chocolate",
  "Fresas",
  "Kiwi",
  "Mango",
  "Piña",
  "Tomate",
  "Cítricos",
  "Naranja",
  "Limón",
  "Ajo",
  "Cebolla",
  "Colorantes artificiales",
  "Conservantes",
  "Glutamato monosódico (MSG)",
  "Aspartamo",
];

export const OTRAS_ALERGIAS = [
  "Polen",
  "Polen de gramíneas",
  "Polen de árboles",
  "Ácaros del polvo",
  "Pelo de animales",
  "Pelo de gato",
  "Pelo de perro",
  "Caspa de animales",
  "Látex",
  "Níquel",
  "Cobalto",
  "Cromo",
  "Picaduras de insectos",
  "Abejas",
  "Avispas",
  "Hormigas",
  "Mosquitos",
  "Moho",
  "Hongos ambientales",
  "Perfumes",
  "Fragancias",
  "Productos químicos",
  "Cloro",
  "Detergentes",
  "Suavizantes",
  "Sol (fotosensibilidad)",
  "Frío",
  "Calor",
  "Plumas",
  "Lana",
  "Algodón",
  "Polvo de madera",
  "Formaldehído",
  "Resinas",
  "Adhesivos",
  "Tintes para cabello",
  "Esmalte de uñas",
  "Cosméticos",
];

export const CONDICIONES_CRONICAS = [
  "Diabetes tipo 1",
  "Diabetes tipo 2",
  "Prediabetes",
  "Hipertensión arterial",
  "Hipotensión",
  "Asma",
  "Asma alérgica",
  "EPOC (Enfermedad Pulmonar Obstructiva Crónica)",
  "Bronquitis crónica",
  "Enfisema",
  "Fibrosis pulmonar",
  "Artritis reumatoide",
  "Osteoartritis",
  "Artritis psoriásica",
  "Gota",
  "Hipotiroidismo",
  "Hipertiroidismo",
  "Tiroiditis de Hashimoto",
  "Enfermedad de Graves",
  "Enfermedad renal crónica",
  "Insuficiencia renal",
  "Cálculos renales",
  "Insuficiencia cardíaca",
  "Enfermedad coronaria",
  "Infarto previo",
  "Angina de pecho",
  "Arritmias cardíacas",
  "Fibrilación auricular",
  "Taquicardia",
  "Bradicardia",
  "Epilepsia",
  "Convulsiones",
  "Migraña crónica",
  "Cefalea tensional",
  "Depresión",
  "Depresión mayor",
  "Ansiedad",
  "Trastorno de ansiedad generalizada",
  "Trastorno de pánico",
  "Trastorno bipolar",
  "Esquizofrenia",
  "Trastorno obsesivo-compulsivo (TOC)",
  "Trastorno de estrés postraumático (TEPT)",
  "Fibromialgia",
  "Síndrome de fatiga crónica",
  "Lupus eritematoso sistémico",
  "Esclerosis múltiple",
  "Enfermedad de Parkinson",
  "Enfermedad de Alzheimer",
  "Demencia",
  "Enfermedad de Crohn",
  "Colitis ulcerosa",
  "Síndrome de intestino irritable",
  "Enfermedad celíaca",
  "Reflujo gastroesofágico (ERGE)",
  "Gastritis crónica",
  "Úlcera péptica",
  "Hepatitis B crónica",
  "Hepatitis C crónica",
  "Cirrosis hepática",
  "Hígado graso",
  "Osteoporosis",
  "Osteopenia",
  "Anemia",
  "Anemia ferropénica",
  "Anemia perniciosa",
  "Talasemia",
  "Hemofilia",
  "Leucemia",
  "Linfoma",
  "Psoriasis",
  "Eczema",
  "Dermatitis atópica",
  "Rosácea",
  "Vitíligo",
  "Glaucoma",
  "Cataratas",
  "Degeneración macular",
  "Retinopatía diabética",
  "Apnea del sueño",
  "Insomnio crónico",
  "Síndrome de piernas inquietas",
  "Enfermedad de Addison",
  "Síndrome de Cushing",
  "Síndrome de ovario poliquístico (SOP)",
  "Endometriosis",
  "Prostatitis crónica",
  "Hiperplasia prostática benigna",
  "VIH/SIDA",
  "Cáncer (especificar tipo)",
  "Enfermedad de Lyme",
  "Sarcoidosis",
];
