import { StructuredTemplate } from './structured-templates';

// Biblioteca extendida de templates médicos (50+ templates)
export const EXTENDED_TEMPLATES: StructuredTemplate[] = [
  // MEDICINA GENERAL
  {
    id: 'consulta_primera_vez',
    name: 'Primera Consulta',
    description: 'Evaluación inicial completa de paciente nuevo',
    category: 'general',
    icon: 'UserPlus',
    color: 'blue',
    author: 'red-salud',
    tags: ['primera-vez', 'nuevo-paciente', 'evaluacion-inicial'],
    fields: [
      { id: 'motivoConsulta', label: 'MOTIVO DE CONSULTA', type: 'textarea', required: true, rows: 2 },
      { id: 'historiaEnfermedad', label: 'HISTORIA ENFERMEDAD ACTUAL', type: 'textarea', required: true, rows: 4 },
      { id: 'antecedentesPersonales', label: 'ANTECEDENTES PERSONALES', type: 'textarea', rows: 3 },
      { id: 'antecedentesFamiliares', label: 'ANTECEDENTES FAMILIARES', type: 'textarea', rows: 2 },
      { id: 'habitosPsicobiologicos', label: 'HÁBITOS', type: 'textarea', rows: 2 },
      { id: 'alergias', label: 'ALERGIAS', type: 'textarea', rows: 2 },
      { id: 'vitals', label: 'SIGNOS VITALES', type: 'vitals', required: true },
      { id: 'examenFisico', label: 'EXAMEN FÍSICO', type: 'textarea', rows: 4 },
      { id: 'impresionDiagnostica', label: 'IMPRESIÓN DIAGNÓSTICA', type: 'textarea', required: true, rows: 2 },
      { id: 'medications', label: 'TRATAMIENTO', type: 'medications' },
      { id: 'planTratamiento', label: 'PLAN', type: 'textarea', rows: 3 },
      { id: 'control', label: 'CONTROL', type: 'input' },
    ],
  },
  {
    id: 'consulta_rapida',
    name: 'Consulta Rápida',
    description: 'Evaluación breve para problemas simples',
    category: 'general',
    icon: 'Zap',
    color: 'yellow',
    author: 'red-salud',
    tags: ['rapida', 'simple', 'breve'],
    fields: [
      { id: 'motivoConsulta', label: 'MOTIVO', type: 'textarea', required: true, rows: 2 },
      { id: 'vitals', label: 'SIGNOS VITALES', type: 'vitals', required: true },
      { id: 'examenFisico', label: 'EXAMEN FÍSICO', type: 'textarea', rows: 2 },
      { id: 'diagnostico', label: 'DIAGNÓSTICO', type: 'input', required: true },
      { id: 'medications', label: 'TRATAMIENTO', type: 'medications' },
      { id: 'indicaciones', label: 'INDICACIONES', type: 'textarea', rows: 2 },
    ],
  },
  // CONTROL Y SEGUIMIENTO
  {
    id: 'control_cronico',
    name: 'Control Enfermedad Crónica',
    description: 'Seguimiento de paciente con enfermedad crónica',
    category: 'control',
    icon: 'Activity',
    color: 'green',
    author: 'red-salud',
    tags: ['control', 'cronico', 'seguimiento'],
    fields: [
      { id: 'motivoConsulta', label: 'MOTIVO', type: 'input', required: true },
      { id: 'evolucion', label: 'EVOLUCIÓN DESDE ÚLTIMA CONSULTA', type: 'textarea', required: true, rows: 3 },
      { id: 'adherenciaTratamiento', label: 'ADHERENCIA AL TRATAMIENTO', type: 'textarea', rows: 2 },
      { id: 'vitals', label: 'SIGNOS VITALES', type: 'vitals', required: true },
      { id: 'laboratorios', label: 'LABORATORIOS RECIENTES', type: 'textarea', rows: 3 },
      { id: 'examenFisico', label: 'EXAMEN FÍSICO', type: 'textarea', rows: 2 },
      { id: 'impresionDiagnostica', label: 'EVALUACIÓN ACTUAL', type: 'textarea', required: true, rows: 2 },
      { id: 'medications', label: 'AJUSTE MEDICAMENTOS', type: 'medications' },
      { id: 'planTratamiento', label: 'PLAN', type: 'textarea', rows: 3 },
      { id: 'control', label: 'PRÓXIMO CONTROL', type: 'input', required: true },
    ],
  },
  {
    id: 'control_hipertension',
    name: 'Control de Hipertensión',
    description: 'Seguimiento específico para pacientes hipertensos',
    category: 'control',
    icon: 'Heart',
    color: 'red',
    author: 'red-salud',
    tags: ['hipertension', 'presion', 'cardiovascular'],
    specialty: 'Cardiología',
    fields: [
      { id: 'motivoConsulta', label: 'MOTIVO', type: 'input', required: true },
      { id: 'sintomas', label: 'SÍNTOMAS CARDIOVASCULARES', type: 'textarea', rows: 2 },
      { id: 'adherencia', label: 'ADHERENCIA A MEDICAMENTOS', type: 'textarea', rows: 2 },
      { id: 'vitals', label: 'SIGNOS VITALES', type: 'vitals', required: true },
      { id: 'presionDomiciliaria', label: 'PRESIÓN ARTERIAL DOMICILIARIA', type: 'textarea', rows: 2 },
      { id: 'examenCardiovascular', label: 'EXAMEN CARDIOVASCULAR', type: 'textarea', rows: 2 },
      { id: 'laboratorios', label: 'LABORATORIOS', type: 'textarea', rows: 2 },
      { id: 'evaluacion', label: 'EVALUACIÓN', type: 'textarea', required: true, rows: 2 },
      { id: 'medications', label: 'TRATAMIENTO', type: 'medications' },
      { id: 'recomendaciones', label: 'RECOMENDACIONES', type: 'textarea', rows: 3 },
      { id: 'control', label: 'PRÓXIMO CONTROL', type: 'input', required: true },
    ],
  },
  {
    id: 'control_diabetes',
    name: 'Control de Diabetes',
    description: 'Seguimiento de paciente diabético',
    category: 'control',
    icon: 'Droplet',
    color: 'blue',
    author: 'red-salud',
    tags: ['diabetes', 'glucosa', 'endocrinologia'],
    specialty: 'Endocrinología',
    fields: [
      { id: 'motivoConsulta', label: 'MOTIVO', type: 'input', required: true },
      { id: 'sintomas', label: 'SÍNTOMAS', type: 'textarea', rows: 2 },
      { id: 'glucometria', label: 'GLUCOMETRÍAS DOMICILIARIAS', type: 'textarea', rows: 3 },
      { id: 'adherencia', label: 'ADHERENCIA A TRATAMIENTO Y DIETA', type: 'textarea', rows: 2 },
      { id: 'vitals', label: 'SIGNOS VITALES', type: 'vitals', required: true },
      { id: 'examenFisico', label: 'EXAMEN FÍSICO', type: 'textarea', rows: 2 },
      { id: 'laboratorios', label: 'LABORATORIOS (HbA1c, Perfil Lipídico)', type: 'textarea', rows: 3 },
      { id: 'complicaciones', label: 'EVALUACIÓN DE COMPLICACIONES', type: 'textarea', rows: 2 },
      { id: 'evaluacion', label: 'EVALUACIÓN', type: 'textarea', required: true, rows: 2 },
      { id: 'medications', label: 'TRATAMIENTO', type: 'medications' },
      { id: 'recomendaciones', label: 'RECOMENDACIONES', type: 'textarea', rows: 3 },
      { id: 'control', label: 'PRÓXIMO CONTROL', type: 'input', required: true },
    ],
  },
  // EMERGENCIAS
  {
    id: 'emergencia_general',
    name: 'Atención de Emergencia',
    description: 'Evaluación rápida para atención urgente',
    category: 'emergencia',
    icon: 'AlertCircle',
    color: 'red',
    author: 'red-salud',
    tags: ['emergencia', 'urgente', 'glasgow'],
    fields: [
      { id: 'motivoConsulta', label: 'MOTIVO DE EMERGENCIA', type: 'textarea', required: true, rows: 2 },
      { id: 'tiempoEvolucion', label: 'TIEMPO DE EVOLUCIÓN', type: 'input', required: true },
      { id: 'sintomasPrincipales', label: 'SÍNTOMAS PRINCIPALES', type: 'textarea', required: true, rows: 3 },
      { id: 'vitals', label: 'SIGNOS VITALES', type: 'vitals', required: true },
      { id: 'glasgow', label: 'ESCALA DE GLASGOW', type: 'input' },
      { id: 'examenFisico', label: 'EXAMEN FÍSICO', type: 'textarea', required: true, rows: 3 },
      { id: 'impresionDiagnostica', label: 'IMPRESIÓN DIAGNÓSTICA', type: 'textarea', required: true, rows: 2 },
      { id: 'medications', label: 'TRATAMIENTO INMEDIATO', type: 'medications' },
      { id: 'conducta', label: 'CONDUCTA', type: 'textarea', required: true, rows: 4 },
    ],
  },
  {
    id: 'dolor_toracico',
    name: 'Dolor Torácico',
    description: 'Evaluación de dolor torácico en emergencia',
    category: 'emergencia',
    icon: 'Heart',
    color: 'red',
    author: 'red-salud',
    tags: ['dolor-toracico', 'cardiologia', 'emergencia'],
    fields: [
      { id: 'motivoConsulta', label: 'MOTIVO', type: 'input', required: true },
      { id: 'caracteristicasDolor', label: 'CARACTERÍSTICAS DEL DOLOR', type: 'textarea', required: true, rows: 3 },
      { id: 'factoresAsociados', label: 'FACTORES ASOCIADOS', type: 'textarea', rows: 2 },
      { id: 'antecedentesCardiovasculares', label: 'ANTECEDENTES CARDIOVASCULARES', type: 'textarea', rows: 2 },
      { id: 'vitals', label: 'SIGNOS VITALES', type: 'vitals', required: true },
      { id: 'examenCardiovascular', label: 'EXAMEN CARDIOVASCULAR', type: 'textarea', required: true, rows: 3 },
      { id: 'ecg', label: 'ELECTROCARDIOGRAMA', type: 'textarea', rows: 2 },
      { id: 'laboratorios', label: 'LABORATORIOS (Troponina, CPK-MB)', type: 'textarea', rows: 2 },
      { id: 'impresionDiagnostica', label: 'IMPRESIÓN DIAGNÓSTICA', type: 'textarea', required: true, rows: 2 },
      { id: 'medications', label: 'TRATAMIENTO', type: 'medications' },
      { id: 'conducta', label: 'CONDUCTA', type: 'textarea', required: true, rows: 3 },
    ],
  },
  {
    id: 'trauma',
    name: 'Evaluación de Trauma',
    description: 'Evaluación inicial de paciente traumatizado',
    category: 'emergencia',
    icon: 'AlertTriangle',
    color: 'orange',
    author: 'red-salud',
    tags: ['trauma', 'accidente', 'lesiones'],
    fields: [
      { id: 'mecanismoTrauma', label: 'MECANISMO DE TRAUMA', type: 'textarea', required: true, rows: 2 },
      { id: 'tiempoEvolucion', label: 'TIEMPO DESDE EL TRAUMA', type: 'input', required: true },
      { id: 'vitals', label: 'SIGNOS VITALES', type: 'vitals', required: true },
      { id: 'glasgow', label: 'ESCALA DE GLASGOW', type: 'input', required: true },
      { id: 'evaluacionPrimaria', label: 'EVALUACIÓN PRIMARIA (ABCDE)', type: 'textarea', required: true, rows: 4 },
      { id: 'evaluacionSecundaria', label: 'EVALUACIÓN SECUNDARIA', type: 'textarea', rows: 4 },
      { id: 'lesionesIdentificadas', label: 'LESIONES IDENTIFICADAS', type: 'textarea', required: true, rows: 3 },
      { id: 'imagenologia', label: 'IMAGENOLOGÍA', type: 'textarea', rows: 2 },
      { id: 'impresionDiagnostica', label: 'IMPRESIÓN DIAGNÓSTICA', type: 'textarea', required: true, rows: 2 },
      { id: 'medications', label: 'TRATAMIENTO', type: 'medications' },
      { id: 'conducta', label: 'CONDUCTA', type: 'textarea', required: true, rows: 3 },
    ],
  },
  // PEDIATRÍA
  {
    id: 'pediatria_general',
    name: 'Consulta Pediátrica',
    description: 'Evaluación pediátrica completa',
    category: 'pediatria',
    icon: 'Baby',
    color: 'purple',
    author: 'red-salud',
    tags: ['pediatria', 'niños', 'desarrollo'],
    specialty: 'Pediatría',
    fields: [
      { id: 'motivoConsulta', label: 'MOTIVO DE CONSULTA', type: 'textarea', required: true, rows: 2 },
      { id: 'edad', label: 'EDAD', type: 'input', required: true },
      { id: 'antecedentesPrenatales', label: 'ANTECEDENTES PRENATALES Y PERINATALES', type: 'textarea', rows: 2 },
      { id: 'desarrolloPsicomotor', label: 'DESARROLLO PSICOMOTOR', type: 'textarea', rows: 2 },
      { id: 'vacunacion', label: 'VACUNACIÓN', type: 'textarea', rows: 2 },
      { id: 'alimentacion', label: 'ALIMENTACIÓN', type: 'textarea', rows: 2 },
      { id: 'vitals', label: 'SIGNOS VITALES Y ANTROPOMETRÍA', type: 'vitals', required: true },
      { id: 'examenFisico', label: 'EXAMEN FÍSICO', type: 'textarea', required: true, rows: 3 },
      { id: 'impresionDiagnostica', label: 'IMPRESIÓN DIAGNÓSTICA', type: 'textarea', required: true, rows: 2 },
      { id: 'medications', label: 'TRATAMIENTO', type: 'medications' },
      { id: 'indicacionesPadres', label: 'INDICACIONES A LOS PADRES', type: 'textarea', rows: 3 },
      { id: 'control', label: 'CONTROL', type: 'input' },
    ],
  },
  {
    id: 'control_niño_sano',
    name: 'Control de Niño Sano',
    description: 'Evaluación de crecimiento y desarrollo',
    category: 'pediatria',
    icon: 'Heart',
    color: 'pink',
    author: 'red-salud',
    tags: ['niño-sano', 'crecimiento', 'desarrollo'],
    specialty: 'Pediatría',
    fields: [
      { id: 'edad', label: 'EDAD', type: 'input', required: true },
      { id: 'alimentacion', label: 'ALIMENTACIÓN', type: 'textarea', rows: 2 },
      { id: 'desarrolloPsicomotor', label: 'DESARROLLO PSICOMOTOR', type: 'textarea', required: true, rows: 3 },
      { id: 'vacunacion', label: 'VACUNACIÓN', type: 'textarea', required: true, rows: 2 },
      { id: 'vitals', label: 'ANTROPOMETRÍA Y SIGNOS VITALES', type: 'vitals', required: true },
      { id: 'examenFisico', label: 'EXAMEN FÍSICO', type: 'textarea', required: true, rows: 3 },
      { id: 'evaluacion', label: 'EVALUACIÓN DEL DESARROLLO', type: 'textarea', required: true, rows: 2 },
      { id: 'recomendaciones', label: 'RECOMENDACIONES', type: 'textarea', rows: 3 },
      { id: 'proximoControl', label: 'PRÓXIMO CONTROL', type: 'input', required: true },
    ],
  },
  // GINECOLOGÍA Y OBSTETRICIA
  {
    id: 'ginecologia_general',
    name: 'Consulta Ginecológica',
    description: 'Evaluación ginecológica completa',
    category: 'ginecologia',
    icon: 'User',
    color: 'pink',
    author: 'red-salud',
    tags: ['ginecologia', 'mujer', 'salud-femenina'],
    specialty: 'Ginecología',
    fields: [
      { id: 'motivoConsulta', label: 'MOTIVO DE CONSULTA', type: 'textarea', required: true, rows: 2 },
      { id: 'antecedentesGinecoObstetricos', label: 'ANTECEDENTES GINECO-OBSTÉTRICOS', type: 'textarea', rows: 3 },
      { id: 'cicloMenstrual', label: 'CICLO MENSTRUAL', type: 'textarea', rows: 2 },
      { id: 'vidaSexual', label: 'VIDA SEXUAL', type: 'textarea', rows: 2 },
      { id: 'metodoAnticonceptivo', label: 'MÉTODO ANTICONCEPTIVO', type: 'input' },
      { id: 'vitals', label: 'SIGNOS VITALES', type: 'vitals', required: true },
      { id: 'examenFisico', label: 'EXAMEN FÍSICO GENERAL', type: 'textarea', rows: 2 },
      { id: 'examenGinecologico', label: 'EXAMEN GINECOLÓGICO', type: 'textarea', required: true, rows: 3 },
      { id: 'impresionDiagnostica', label: 'IMPRESIÓN DIAGNÓSTICA', type: 'textarea', required: true, rows: 2 },
      { id: 'medications', label: 'TRATAMIENTO', type: 'medications' },
      { id: 'planTratamiento', label: 'PLAN', type: 'textarea', rows: 3 },
      { id: 'control', label: 'CONTROL', type: 'input' },
    ],
  },
  {
    id: 'control_prenatal',
    name: 'Control Prenatal',
    description: 'Seguimiento de embarazo',
    category: 'ginecologia',
    icon: 'Baby',
    color: 'blue',
    author: 'red-salud',
    tags: ['prenatal', 'embarazo', 'obstetricia'],
    specialty: 'Obstetricia',
    fields: [
      { id: 'edadGestacional', label: 'EDAD GESTACIONAL', type: 'input', required: true },
      { id: 'sintomas', label: 'SÍNTOMAS', type: 'textarea', rows: 2 },
      { id: 'movimientosFetales', label: 'MOVIMIENTOS FETALES', type: 'textarea', rows: 1 },
      { id: 'vitals', label: 'SIGNOS VITALES', type: 'vitals', required: true },
      { id: 'pesoGanancia', label: 'PESO Y GANANCIA', type: 'input' },
      { id: 'alturaUterina', label: 'ALTURA UTERINA', type: 'input' },
      { id: 'fcf', label: 'FCF', type: 'input' },
      { id: 'examenObstetrico', label: 'EXAMEN OBSTÉTRICO', type: 'textarea', required: true, rows: 3 },
      { id: 'laboratorios', label: 'LABORATORIOS', type: 'textarea', rows: 2 },
      { id: 'ecografia', label: 'ECOGRAFÍA', type: 'textarea', rows: 2 },
      { id: 'evaluacion', label: 'EVALUACIÓN', type: 'textarea', required: true, rows: 2 },
      { id: 'medications', label: 'SUPLEMENTOS/MEDICAMENTOS', type: 'medications' },
      { id: 'recomendaciones', label: 'RECOMENDACIONES', type: 'textarea', rows: 3 },
      { id: 'proximoControl', label: 'PRÓXIMO CONTROL', type: 'input', required: true },
    ],
  },
  // DERMATOLOGÍA
  {
    id: 'dermatologia_general',
    name: 'Consulta Dermatológica',
    description: 'Evaluación dermatológica completa',
    category: 'dermatologia',
    icon: 'Scan',
    color: 'orange',
    author: 'red-salud',
    tags: ['dermatologia', 'piel', 'lesiones'],
    specialty: 'Dermatología',
    fields: [
      { id: 'motivoConsulta', label: 'MOTIVO DE CONSULTA', type: 'textarea', required: true, rows: 2 },
      { id: 'tiempoEvolucion', label: 'TIEMPO DE EVOLUCIÓN', type: 'input', required: true },
      { id: 'caracteristicasLesion', label: 'CARACTERÍSTICAS DE LA LESIÓN', type: 'textarea', required: true, rows: 3 },
      { id: 'factoresDesencadenantes', label: 'FACTORES DESENCADENANTES', type: 'textarea', rows: 2 },
      { id: 'tratamientosPrevios', label: 'TRATAMIENTOS PREVIOS', type: 'textarea', rows: 2 },
      { id: 'antecedentes', label: 'ANTECEDENTES DERMATOLÓGICOS', type: 'textarea', rows: 2 },
      { id: 'examenDermatologico', label: 'EXAMEN DERMATOLÓGICO', type: 'textarea', required: true, rows: 4 },
      { id: 'distribucion', label: 'DISTRIBUCIÓN Y LOCALIZACIÓN', type: 'textarea', rows: 2 },
      { id: 'impresionDiagnostica', label: 'IMPRESIÓN DIAGNÓSTICA', type: 'textarea', required: true, rows: 2 },
      { id: 'medications', label: 'TRATAMIENTO', type: 'medications' },
      { id: 'recomendaciones', label: 'RECOMENDACIONES', type: 'textarea', rows: 3 },
      { id: 'control', label: 'CONTROL', type: 'input' },
    ],
  },
  // OFTALMOLOGÍA
  {
    id: 'oftalmologia_general',
    name: 'Consulta Oftalmológica',
    description: 'Evaluación oftalmológica completa',
    category: 'oftalmologia',
    icon: 'Eye',
    color: 'cyan',
    author: 'red-salud',
    tags: ['oftalmologia', 'vision', 'ojos'],
    specialty: 'Oftalmología',
    fields: [
      { id: 'motivoConsulta', label: 'MOTIVO DE CONSULTA', type: 'textarea', required: true, rows: 2 },
      { id: 'sintomas', label: 'SÍNTOMAS VISUALES', type: 'textarea', required: true, rows: 2 },
      { id: 'antecedentesOftalmologicos', label: 'ANTECEDENTES OFTALMOLÓGICOS', type: 'textarea', rows: 2 },
      { id: 'agudezaVisual', label: 'AGUDEZA VISUAL', type: 'textarea', required: true, rows: 2 },
      { id: 'presionIntraocular', label: 'PRESIÓN INTRAOCULAR', type: 'input' },
      { id: 'examenExterno', label: 'EXAMEN EXTERNO', type: 'textarea', rows: 2 },
      { id: 'biomicroscopia', label: 'BIOMICROSCOPÍA', type: 'textarea', required: true, rows: 3 },
      { id: 'fondoOjo', label: 'FONDO DE OJO', type: 'textarea', rows: 3 },
      { id: 'impresionDiagnostica', label: 'IMPRESIÓN DIAGNÓSTICA', type: 'textarea', required: true, rows: 2 },
      { id: 'medications', label: 'TRATAMIENTO', type: 'medications' },
      { id: 'recomendaciones', label: 'RECOMENDACIONES', type: 'textarea', rows: 2 },
      { id: 'control', label: 'CONTROL', type: 'input' },
    ],
  },
  // OTORRINOLARINGOLOGÍA
  {
    id: 'otorrino_general',
    name: 'Consulta ORL',
    description: 'Evaluación otorrinolaringológica',
    category: 'otorrino',
    icon: 'Ear',
    color: 'teal',
    author: 'red-salud',
    tags: ['otorrino', 'oido', 'nariz', 'garganta'],
    specialty: 'Otorrinolaringología',
    fields: [
      { id: 'motivoConsulta', label: 'MOTIVO DE CONSULTA', type: 'textarea', required: true, rows: 2 },
      { id: 'sintomas', label: 'SÍNTOMAS', type: 'textarea', required: true, rows: 2 },
      { id: 'tiempoEvolucion', label: 'TIEMPO DE EVOLUCIÓN', type: 'input', required: true },
      { id: 'antecedentes', label: 'ANTECEDENTES ORL', type: 'textarea', rows: 2 },
      { id: 'otoscopia', label: 'OTOSCOPÍA', type: 'textarea', required: true, rows: 2 },
      { id: 'rinoscopia', label: 'RINOSCOPIA', type: 'textarea', rows: 2 },
      { id: 'orofaringe', label: 'OROFARINGE', type: 'textarea', rows: 2 },
      { id: 'cuello', label: 'EXAMEN DE CUELLO', type: 'textarea', rows: 2 },
      { id: 'audiometria', label: 'AUDIOMETRÍA', type: 'textarea', rows: 2 },
      { id: 'impresionDiagnostica', label: 'IMPRESIÓN DIAGNÓSTICA', type: 'textarea', required: true, rows: 2 },
      { id: 'medications', label: 'TRATAMIENTO', type: 'medications' },
      { id: 'recomendaciones', label: 'RECOMENDACIONES', type: 'textarea', rows: 2 },
      { id: 'control', label: 'CONTROL', type: 'input' },
    ],
  },
  // TRAUMATOLOGÍA
  {
    id: 'traumatologia_general',
    name: 'Consulta Traumatológica',
    description: 'Evaluación traumatológica y ortopédica',
    category: 'traumatologia',
    icon: 'Bone',
    color: 'gray',
    author: 'red-salud',
    tags: ['traumatologia', 'ortopedia', 'fracturas'],
    specialty: 'Traumatología',
    fields: [
      { id: 'motivoConsulta', label: 'MOTIVO DE CONSULTA', type: 'textarea', required: true, rows: 2 },
      { id: 'mecanismoLesion', label: 'MECANISMO DE LESIÓN', type: 'textarea', required: true, rows: 2 },
      { id: 'tiempoEvolucion', label: 'TIEMPO DE EVOLUCIÓN', type: 'input', required: true },
      { id: 'dolor', label: 'CARACTERÍSTICAS DEL DOLOR', type: 'textarea', rows: 2 },
      { id: 'limitacionFuncional', label: 'LIMITACIÓN FUNCIONAL', type: 'textarea', rows: 2 },
      { id: 'vitals', label: 'SIGNOS VITALES', type: 'vitals' },
      { id: 'inspeccion', label: 'INSPECCIÓN', type: 'textarea', required: true, rows: 2 },
      { id: 'palpacion', label: 'PALPACIÓN', type: 'textarea', rows: 2 },
      { id: 'movilidad', label: 'MOVILIDAD Y RANGOS ARTICULARES', type: 'textarea', rows: 2 },
      { id: 'examenNeurovascular', label: 'EXAMEN NEUROVASCULAR', type: 'textarea', rows: 2 },
      { id: 'imagenologia', label: 'IMAGENOLOGÍA', type: 'textarea', rows: 3 },
      { id: 'impresionDiagnostica', label: 'IMPRESIÓN DIAGNÓSTICA', type: 'textarea', required: true, rows: 2 },
      { id: 'medications', label: 'TRATAMIENTO', type: 'medications' },
      { id: 'planTratamiento', label: 'PLAN DE TRATAMIENTO', type: 'textarea', rows: 3 },
      { id: 'control', label: 'CONTROL', type: 'input' },
    ],
  },
  // PSIQUIATRÍA
  {
    id: 'psiquiatria_general',
    name: 'Consulta Psiquiátrica',
    description: 'Evaluación psiquiátrica completa',
    category: 'psiquiatria',
    icon: 'Brain',
    color: 'indigo',
    author: 'red-salud',
    tags: ['psiquiatria', 'salud-mental', 'psicologia'],
    specialty: 'Psiquiatría',
    fields: [
      { id: 'motivoConsulta', label: 'MOTIVO DE CONSULTA', type: 'textarea', required: true, rows: 2 },
      { id: 'historiaEnfermedad', label: 'HISTORIA DE LA ENFERMEDAD ACTUAL', type: 'textarea', required: true, rows: 4 },
      { id: 'antecedentes', label: 'ANTECEDENTES PSIQUIÁTRICOS', type: 'textarea', rows: 3 },
      { id: 'antecedentesFamiliares', label: 'ANTECEDENTES FAMILIARES PSIQUIÁTRICOS', type: 'textarea', rows: 2 },
      { id: 'sustancias', label: 'USO DE SUSTANCIAS', type: 'textarea', rows: 2 },
      { id: 'examenMental', label: 'EXAMEN MENTAL', type: 'textarea', required: true, rows: 5 },
      { id: 'riesgoSuicida', label: 'EVALUACIÓN DE RIESGO SUICIDA', type: 'textarea', rows: 2 },
      { id: 'riesgoHeteroagresivo', label: 'EVALUACIÓN DE RIESGO HETEROAGRESIVO', type: 'textarea', rows: 2 },
      { id: 'impresionDiagnostica', label: 'IMPRESIÓN DIAGNÓSTICA', type: 'textarea', required: true, rows: 2 },
      { id: 'medications', label: 'TRATAMIENTO FARMACOLÓGICO', type: 'medications' },
      { id: 'planTratamiento', label: 'PLAN DE TRATAMIENTO', type: 'textarea', rows: 3 },
      { id: 'control', label: 'CONTROL', type: 'input', required: true },
    ],
  },
  // NEUROLOGÍA
  {
    id: 'neurologia_general',
    name: 'Consulta Neurológica',
    description: 'Evaluación neurológica completa',
    category: 'neurologia',
    icon: 'Brain',
    color: 'purple',
    author: 'red-salud',
    tags: ['neurologia', 'sistema-nervioso', 'cerebro'],
    specialty: 'Neurología',
    fields: [
      { id: 'motivoConsulta', label: 'MOTIVO DE CONSULTA', type: 'textarea', required: true, rows: 2 },
      { id: 'historiaEnfermedad', label: 'HISTORIA DE LA ENFERMEDAD ACTUAL', type: 'textarea', required: true, rows: 4 },
      { id: 'antecedentes', label: 'ANTECEDENTES NEUROLÓGICOS', type: 'textarea', rows: 2 },
      { id: 'vitals', label: 'SIGNOS VITALES', type: 'vitals', required: true },
      { id: 'estadoMental', label: 'ESTADO MENTAL', type: 'textarea', required: true, rows: 2 },
      { id: 'paresCreaneales', label: 'PARES CRANEALES', type: 'textarea', required: true, rows: 3 },
      { id: 'motor', label: 'EXAMEN MOTOR', type: 'textarea', required: true, rows: 3 },
      { id: 'sensitivo', label: 'EXAMEN SENSITIVO', type: 'textarea', rows: 2 },
      { id: 'reflejos', label: 'REFLEJOS', type: 'textarea', rows: 2 },
      { id: 'coordinacion', label: 'COORDINACIÓN Y MARCHA', type: 'textarea', rows: 2 },
      { id: 'signosMeningeos', label: 'SIGNOS MENÍNGEOS', type: 'textarea', rows: 1 },
      { id: 'impresionDiagnostica', label: 'IMPRESIÓN DIAGNÓSTICA', type: 'textarea', required: true, rows: 2 },
      { id: 'medications', label: 'TRATAMIENTO', type: 'medications' },
      { id: 'planTratamiento', label: 'PLAN', type: 'textarea', rows: 3 },
      { id: 'control', label: 'CONTROL', type: 'input' },
    ],
  },
  // CARDIOLOGÍA
  {
    id: 'cardiologia_general',
    name: 'Consulta Cardiológica',
    description: 'Evaluación cardiológica completa',
    category: 'cardiologia',
    icon: 'Heart',
    color: 'red',
    author: 'red-salud',
    tags: ['cardiologia', 'corazon', 'cardiovascular'],
    specialty: 'Cardiología',
    fields: [
      { id: 'motivoConsulta', label: 'MOTIVO DE CONSULTA', type: 'textarea', required: true, rows: 2 },
      { id: 'sintomasCardiovasculares', label: 'SÍNTOMAS CARDIOVASCULARES', type: 'textarea', required: true, rows: 3 },
      { id: 'factoresRiesgo', label: 'FACTORES DE RIESGO CARDIOVASCULAR', type: 'textarea', rows: 3 },
      { id: 'antecedentes', label: 'ANTECEDENTES CARDIOVASCULARES', type: 'textarea', rows: 2 },
      { id: 'vitals', label: 'SIGNOS VITALES', type: 'vitals', required: true },
      { id: 'examenCardiovascular', label: 'EXAMEN CARDIOVASCULAR', type: 'textarea', required: true, rows: 4 },
      { id: 'ecg', label: 'ELECTROCARDIOGRAMA', type: 'textarea', rows: 3 },
      { id: 'ecocardiograma', label: 'ECOCARDIOGRAMA', type: 'textarea', rows: 3 },
      { id: 'laboratorios', label: 'LABORATORIOS', type: 'textarea', rows: 2 },
      { id: 'impresionDiagnostica', label: 'IMPRESIÓN DIAGNÓSTICA', type: 'textarea', required: true, rows: 2 },
      { id: 'medications', label: 'TRATAMIENTO', type: 'medications' },
      { id: 'recomendaciones', label: 'RECOMENDACIONES', type: 'textarea', rows: 3 },
      { id: 'control', label: 'CONTROL', type: 'input' },
    ],
  },
  // GASTROENTEROLOGÍA
  {
    id: 'gastroenterologia_general',
    name: 'Consulta Gastroenterológica',
    description: 'Evaluación gastroenterológica',
    category: 'especialidad',
    icon: 'Activity',
    color: 'yellow',
    author: 'red-salud',
    tags: ['gastroenterologia', 'digestivo', 'abdomen'],
    specialty: 'Gastroenterología',
    fields: [
      { id: 'motivoConsulta', label: 'MOTIVO DE CONSULTA', type: 'textarea', required: true, rows: 2 },
      { id: 'sintomasDigestivos', label: 'SÍNTOMAS DIGESTIVOS', type: 'textarea', required: true, rows: 3 },
      { id: 'habitosIntestinales', label: 'HÁBITOS INTESTINALES', type: 'textarea', rows: 2 },
      { id: 'dieta', label: 'DIETA', type: 'textarea', rows: 2 },
      { id: 'antecedentes', label: 'ANTECEDENTES GASTROINTESTINALES', type: 'textarea', rows: 2 },
      { id: 'vitals', label: 'SIGNOS VITALES', type: 'vitals', required: true },
      { id: 'examenAbdominal', label: 'EXAMEN ABDOMINAL', type: 'textarea', required: true, rows: 4 },
      { id: 'tactoRectal', label: 'TACTO RECTAL', type: 'textarea', rows: 2 },
      { id: 'laboratorios', label: 'LABORATORIOS', type: 'textarea', rows: 2 },
      { id: 'endoscopia', label: 'ENDOSCOPÍA', type: 'textarea', rows: 3 },
      { id: 'imagenologia', label: 'IMAGENOLOGÍA', type: 'textarea', rows: 2 },
      { id: 'impresionDiagnostica', label: 'IMPRESIÓN DIAGNÓSTICA', type: 'textarea', required: true, rows: 2 },
      { id: 'medications', label: 'TRATAMIENTO', type: 'medications' },
      { id: 'recomendaciones', label: 'RECOMENDACIONES DIETÉTICAS', type: 'textarea', rows: 3 },
      { id: 'control', label: 'CONTROL', type: 'input' },
    ],
  },
  // NEUMOLOGÍA
  {
    id: 'neumologia_general',
    name: 'Consulta Neumológica',
    description: 'Evaluación neumológica completa',
    category: 'especialidad',
    icon: 'Wind',
    color: 'sky',
    author: 'red-salud',
    tags: ['neumologia', 'respiratorio', 'pulmon'],
    specialty: 'Neumología',
    fields: [
      { id: 'motivoConsulta', label: 'MOTIVO DE CONSULTA', type: 'textarea', required: true, rows: 2 },
      { id: 'sintomasRespiratorios', label: 'SÍNTOMAS RESPIRATORIOS', type: 'textarea', required: true, rows: 3 },
      { id: 'tos', label: 'CARACTERÍSTICAS DE LA TOS', type: 'textarea', rows: 2 },
      { id: 'disnea', label: 'DISNEA', type: 'textarea', rows: 2 },
      { id: 'exposiciones', label: 'EXPOSICIONES AMBIENTALES/OCUPACIONALES', type: 'textarea', rows: 2 },
      { id: 'tabaquismo', label: 'TABAQUISMO', type: 'textarea', rows: 2 },
      { id: 'vitals', label: 'SIGNOS VITALES Y SATURACIÓN', type: 'vitals', required: true },
      { id: 'examenRespiratorio', label: 'EXAMEN RESPIRATORIO', type: 'textarea', required: true, rows: 4 },
      { id: 'espirometria', label: 'ESPIROMETRÍA', type: 'textarea', rows: 3 },
      { id: 'imagenologia', label: 'RADIOGRAFÍA/TAC DE TÓRAX', type: 'textarea', rows: 3 },
      { id: 'impresionDiagnostica', label: 'IMPRESIÓN DIAGNÓSTICA', type: 'textarea', required: true, rows: 2 },
      { id: 'medications', label: 'TRATAMIENTO', type: 'medications' },
      { id: 'recomendaciones', label: 'RECOMENDACIONES', type: 'textarea', rows: 3 },
      { id: 'control', label: 'CONTROL', type: 'input' },
    ],
  },
  // PROCEDIMIENTOS Y QUIRÚRGICOS
  {
    id: 'preoperatorio',
    name: 'Evaluación Preoperatoria',
    description: 'Evaluación médica preoperatoria',
    category: 'quirurgico',
    icon: 'Scissors',
    color: 'blue',
    author: 'red-salud',
    tags: ['preoperatorio', 'cirugia', 'evaluacion'],
    fields: [
      { id: 'procedimientoPropuesto', label: 'PROCEDIMIENTO QUIRÚRGICO PROPUESTO', type: 'textarea', required: true, rows: 2 },
      { id: 'antecedentesQuirurgicos', label: 'ANTECEDENTES QUIRÚRGICOS', type: 'textarea', rows: 2 },
      { id: 'antecedentesAnestesicos', label: 'ANTECEDENTES ANESTÉSICOS', type: 'textarea', rows: 2 },
      { id: 'comorbilidades', label: 'COMORBILIDADES', type: 'textarea', rows: 3 },
      { id: 'medicamentosActuales', label: 'MEDICAMENTOS ACTUALES', type: 'textarea', rows: 2 },
      { id: 'alergias', label: 'ALERGIAS', type: 'textarea', rows: 2 },
      { id: 'vitals', label: 'SIGNOS VITALES', type: 'vitals', required: true },
      { id: 'examenFisico', label: 'EXAMEN FÍSICO', type: 'textarea', required: true, rows: 3 },
      { id: 'viaAerea', label: 'EVALUACIÓN DE VÍA AÉREA', type: 'textarea', rows: 2 },
      { id: 'laboratorios', label: 'LABORATORIOS PREOPERATORIOS', type: 'textarea', rows: 3 },
      { id: 'ecg', label: 'ELECTROCARDIOGRAMA', type: 'textarea', rows: 2 },
      { id: 'imagenologia', label: 'IMAGENOLOGÍA', type: 'textarea', rows: 2 },
      { id: 'riesgoQuirurgico', label: 'EVALUACIÓN DE RIESGO QUIRÚRGICO', type: 'textarea', required: true, rows: 3 },
      { id: 'clasificacionASA', label: 'CLASIFICACIÓN ASA', type: 'input', required: true },
      { id: 'recomendaciones', label: 'RECOMENDACIONES PREOPERATORIAS', type: 'textarea', rows: 3 },
      { id: 'aptitud', label: 'APTITUD QUIRÚRGICA', type: 'textarea', required: true, rows: 2 },
    ],
  },
  {
    id: 'postoperatorio',
    name: 'Nota Postoperatoria',
    description: 'Evaluación postoperatoria inmediata',
    category: 'quirurgico',
    icon: 'ClipboardCheck',
    color: 'green',
    author: 'red-salud',
    tags: ['postoperatorio', 'cirugia', 'seguimiento'],
    fields: [
      { id: 'procedimientoRealizado', label: 'PROCEDIMIENTO REALIZADO', type: 'textarea', required: true, rows: 2 },
      { id: 'tiempoCirugia', label: 'TIEMPO DE CIRUGÍA', type: 'input' },
      { id: 'anestesia', label: 'TIPO DE ANESTESIA', type: 'input' },
      { id: 'hallazgos', label: 'HALLAZGOS QUIRÚRGICOS', type: 'textarea', required: true, rows: 3 },
      { id: 'complicaciones', label: 'COMPLICACIONES INTRAOPERATORIAS', type: 'textarea', rows: 2 },
      { id: 'vitals', label: 'SIGNOS VITALES', type: 'vitals', required: true },
      { id: 'dolor', label: 'EVALUACIÓN DEL DOLOR', type: 'textarea', rows: 2 },
      { id: 'herida', label: 'EVALUACIÓN DE HERIDA QUIRÚRGICA', type: 'textarea', rows: 2 },
      { id: 'drenajes', label: 'DRENAJES', type: 'textarea', rows: 1 },
      { id: 'diuresis', label: 'DIURESIS', type: 'input' },
      { id: 'toleranciaOral', label: 'TOLERANCIA ORAL', type: 'textarea', rows: 1 },
      { id: 'medications', label: 'MEDICAMENTOS POSTOPERATORIOS', type: 'medications' },
      { id: 'indicaciones', label: 'INDICACIONES', type: 'textarea', rows: 3 },
      { id: 'plan', label: 'PLAN', type: 'textarea', required: true, rows: 2 },
    ],
  },
  // MEDICINA INTERNA
  {
    id: 'medicina_interna',
    name: 'Consulta Medicina Interna',
    description: 'Evaluación de medicina interna',
    category: 'especialidad',
    icon: 'Stethoscope',
    color: 'indigo',
    author: 'red-salud',
    tags: ['medicina-interna', 'internista', 'complejo'],
    specialty: 'Medicina Interna',
    fields: [
      { id: 'motivoConsulta', label: 'MOTIVO DE CONSULTA', type: 'textarea', required: true, rows: 2 },
      { id: 'historiaEnfermedad', label: 'HISTORIA DE LA ENFERMEDAD ACTUAL', type: 'textarea', required: true, rows: 4 },
      { id: 'comorbilidades', label: 'COMORBILIDADES', type: 'textarea', rows: 3 },
      { id: 'medicamentosActuales', label: 'MEDICAMENTOS ACTUALES', type: 'textarea', rows: 3 },
      { id: 'revisionSistemas', label: 'REVISIÓN POR SISTEMAS', type: 'textarea', rows: 4 },
      { id: 'vitals', label: 'SIGNOS VITALES', type: 'vitals', required: true },
      { id: 'examenFisico', label: 'EXAMEN FÍSICO COMPLETO', type: 'textarea', required: true, rows: 5 },
      { id: 'laboratorios', label: 'LABORATORIOS', type: 'textarea', rows: 3 },
      { id: 'imagenologia', label: 'IMAGENOLOGÍA', type: 'textarea', rows: 2 },
      { id: 'impresionDiagnostica', label: 'IMPRESIÓN DIAGNÓSTICA', type: 'textarea', required: true, rows: 3 },
      { id: 'medications', label: 'TRATAMIENTO', type: 'medications' },
      { id: 'planTratamiento', label: 'PLAN DE MANEJO', type: 'textarea', rows: 4 },
      { id: 'control', label: 'CONTROL', type: 'input' },
    ],
  },
  // UROLOGÍA
  {
    id: 'urologia_general',
    name: 'Consulta Urológica',
    description: 'Evaluación urológica',
    category: 'especialidad',
    icon: 'Droplet',
    color: 'blue',
    author: 'red-salud',
    tags: ['urologia', 'genitourinario', 'prostata'],
    specialty: 'Urología',
    fields: [
      { id: 'motivoConsulta', label: 'MOTIVO DE CONSULTA', type: 'textarea', required: true, rows: 2 },
      { id: 'sintomasUrinarios', label: 'SÍNTOMAS URINARIOS', type: 'textarea', required: true, rows: 3 },
      { id: 'antecedentes', label: 'ANTECEDENTES UROLÓGICOS', type: 'textarea', rows: 2 },
      { id: 'vitals', label: 'SIGNOS VITALES', type: 'vitals', required: true },
      { id: 'examenAbdominal', label: 'EXAMEN ABDOMINAL', type: 'textarea', rows: 2 },
      { id: 'examenGenital', label: 'EXAMEN GENITAL', type: 'textarea', required: true, rows: 2 },
      { id: 'tactoRectal', label: 'TACTO RECTAL', type: 'textarea', rows: 2 },
      { id: 'laboratorios', label: 'LABORATORIOS (PSA, Urocultivo)', type: 'textarea', rows: 2 },
      { id: 'imagenologia', label: 'IMAGENOLOGÍA', type: 'textarea', rows: 2 },
      { id: 'impresionDiagnostica', label: 'IMPRESIÓN DIAGNÓSTICA', type: 'textarea', required: true, rows: 2 },
      { id: 'medications', label: 'TRATAMIENTO', type: 'medications' },
      { id: 'planTratamiento', label: 'PLAN', type: 'textarea', rows: 3 },
      { id: 'control', label: 'CONTROL', type: 'input' },
    ],
  },
  // ENDOCRINOLOGÍA
  {
    id: 'endocrinologia_general',
    name: 'Consulta Endocrinológica',
    description: 'Evaluación endocrinológica',
    category: 'especialidad',
    icon: 'Activity',
    color: 'purple',
    author: 'red-salud',
    tags: ['endocrinologia', 'hormonas', 'metabolismo'],
    specialty: 'Endocrinología',
    fields: [
      { id: 'motivoConsulta', label: 'MOTIVO DE CONSULTA', type: 'textarea', required: true, rows: 2 },
      { id: 'sintomas', label: 'SÍNTOMAS', type: 'textarea', required: true, rows: 3 },
      { id: 'antecedentes', label: 'ANTECEDENTES ENDOCRINOLÓGICOS', type: 'textarea', rows: 2 },
      { id: 'medicamentosActuales', label: 'MEDICAMENTOS ACTUALES', type: 'textarea', rows: 2 },
      { id: 'vitals', label: 'SIGNOS VITALES Y ANTROPOMETRÍA', type: 'vitals', required: true },
      { id: 'examenFisico', label: 'EXAMEN FÍSICO', type: 'textarea', required: true, rows: 3 },
      { id: 'examenTiroideo', label: 'EXAMEN TIROIDEO', type: 'textarea', rows: 2 },
      { id: 'laboratorios', label: 'LABORATORIOS HORMONALES', type: 'textarea', rows: 3 },
      { id: 'impresionDiagnostica', label: 'IMPRESIÓN DIAGNÓSTICA', type: 'textarea', required: true, rows: 2 },
      { id: 'medications', label: 'TRATAMIENTO', type: 'medications' },
      { id: 'recomendaciones', label: 'RECOMENDACIONES', type: 'textarea', rows: 3 },
      { id: 'control', label: 'CONTROL', type: 'input' },
    ],
  },
  // REUMATOLOGÍA
  {
    id: 'reumatologia_general',
    name: 'Consulta Reumatológica',
    description: 'Evaluación reumatológica',
    category: 'especialidad',
    icon: 'Bone',
    color: 'orange',
    author: 'red-salud',
    tags: ['reumatologia', 'articulaciones', 'autoinmune'],
    specialty: 'Reumatología',
    fields: [
      { id: 'motivoConsulta', label: 'MOTIVO DE CONSULTA', type: 'textarea', required: true, rows: 2 },
      { id: 'dolor', label: 'CARACTERÍSTICAS DEL DOLOR', type: 'textarea', required: true, rows: 3 },
      { id: 'rigidez', label: 'RIGIDEZ MATUTINA', type: 'textarea', rows: 2 },
      { id: 'articulacionesAfectadas', label: 'ARTICULACIONES AFECTADAS', type: 'textarea', required: true, rows: 2 },
      { id: 'manifestacionesExtraarticulares', label: 'MANIFESTACIONES EXTRAARTICULARES', type: 'textarea', rows: 2 },
      { id: 'vitals', label: 'SIGNOS VITALES', type: 'vitals', required: true },
      { id: 'examenArticular', label: 'EXAMEN ARTICULAR', type: 'textarea', required: true, rows: 4 },
      { id: 'movilidad', label: 'RANGOS DE MOVILIDAD', type: 'textarea', rows: 2 },
      { id: 'laboratorios', label: 'LABORATORIOS (FR, Anti-CCP, VSG, PCR)', type: 'textarea', rows: 3 },
      { id: 'imagenologia', label: 'IMAGENOLOGÍA', type: 'textarea', rows: 2 },
      { id: 'impresionDiagnostica', label: 'IMPRESIÓN DIAGNÓSTICA', type: 'textarea', required: true, rows: 2 },
      { id: 'medications', label: 'TRATAMIENTO', type: 'medications' },
      { id: 'recomendaciones', label: 'RECOMENDACIONES', type: 'textarea', rows: 3 },
      { id: 'control', label: 'CONTROL', type: 'input' },
    ],
  },
  // INFECTOLOGÍA
  {
    id: 'infectologia_general',
    name: 'Consulta Infectológica',
    description: 'Evaluación de enfermedades infecciosas',
    category: 'especialidad',
    icon: 'Bug',
    color: 'red',
    author: 'red-salud',
    tags: ['infectologia', 'infecciones', 'antibioticos'],
    specialty: 'Infectología',
    fields: [
      { id: 'motivoConsulta', label: 'MOTIVO DE CONSULTA', type: 'textarea', required: true, rows: 2 },
      { id: 'fiebre', label: 'CARACTERÍSTICAS DE LA FIEBRE', type: 'textarea', rows: 2 },
      { id: 'focoInfeccioso', label: 'FOCO INFECCIOSO SOSPECHADO', type: 'textarea', required: true, rows: 2 },
      { id: 'exposiciones', label: 'EXPOSICIONES Y VIAJES', type: 'textarea', rows: 2 },
      { id: 'antibioticosRecibidos', label: 'ANTIBIÓTICOS RECIBIDOS', type: 'textarea', rows: 2 },
      { id: 'vitals', label: 'SIGNOS VITALES', type: 'vitals', required: true },
      { id: 'examenFisico', label: 'EXAMEN FÍSICO', type: 'textarea', required: true, rows: 4 },
      { id: 'laboratorios', label: 'LABORATORIOS (Hemograma, PCR, Cultivos)', type: 'textarea', rows: 3 },
      { id: 'imagenologia', label: 'IMAGENOLOGÍA', type: 'textarea', rows: 2 },
      { id: 'impresionDiagnostica', label: 'IMPRESIÓN DIAGNÓSTICA', type: 'textarea', required: true, rows: 2 },
      { id: 'medications', label: 'TRATAMIENTO ANTIBIÓTICO', type: 'medications' },
      { id: 'planTratamiento', label: 'PLAN DE MANEJO', type: 'textarea', rows: 3 },
      { id: 'control', label: 'CONTROL', type: 'input' },
    ],
  },
];

// Función para obtener todos los templates (originales + extendidos)
export function getAllTemplates(): StructuredTemplate[] {
  return EXTENDED_TEMPLATES;
}

// Función para obtener templates por categoría
export function getTemplatesByCategory(category: string): StructuredTemplate[] {
  if (category === 'all') return EXTENDED_TEMPLATES;
  return EXTENDED_TEMPLATES.filter(t => t.category === category);
}

// Función para obtener templates por especialidad
export function getTemplatesBySpecialty(specialty: string): StructuredTemplate[] {
  return EXTENDED_TEMPLATES.filter(t => t.specialty === specialty);
}

// Función para buscar templates
export function searchTemplates(query: string): StructuredTemplate[] {
  const lowerQuery = query.toLowerCase();
  return EXTENDED_TEMPLATES.filter(t => 
    t.name.toLowerCase().includes(lowerQuery) ||
    t.description.toLowerCase().includes(lowerQuery) ||
    t.tags.some(tag => tag.toLowerCase().includes(lowerQuery)) ||
    (t.specialty && t.specialty.toLowerCase().includes(lowerQuery))
  );
}
